// scripts/build_full_periodic_data.js
import fs from 'fs';
import path from 'path';

// Complete dataset for elements 1 to 118
const elements = [
  // 1-10
  {
    number: 1, symbol: 'H', name: 'Hydrogen', atomicMass: 1.008, category: 'reactive-nonmetal',
    group: 1, period: 1, block: 's', state: 'Gas',
    electronConfiguration: '1s¹', electronsPerShell: [1],
    electronegativity: 2.20, meltingPoint: 14.01, boilingPoint: 20.28, density: 0.08988,
    atomicRadius: 53, ionizationEnergy: 1312.0, electronAffinity: 72.8,
    oxidationStates: [-1, 1], discoveredBy: 'Henry Cavendish', yearDiscovered: 1766,
    summary: 'Hydrogen is the lightest, most abundant chemical element in the universe, constituting roughly 75% of all baryonic mass.',
    occurrence: 'Abundant in water, organic matter, stellar atmospheres, and interstellar gas clouds.',
    extraction: 'Primarily obtained via steam methane reforming, water electrolysis, and coal gasification.',
    applications: ['Ammonia synthesis (Haber process)', 'Clean fuel cells and rocketry', 'Petroleum hydrocracking', 'Hydrogenation of fats and oils'],
    importantCompounds: [
      { formula: 'H2O', name: 'Water', use: 'Universal solvent and essential for life' },
      { formula: 'NH3', name: 'Ammonia', use: 'Fertilizers and nitrogenous chemicals' },
      { formula: 'HCl', name: 'Hydrochloric Acid', use: 'Industrial pickling and chemical synthesis' },
      { formula: 'H2O2', name: 'Hydrogen Peroxide', use: 'Bleaching agent and disinfectant' }
    ],
    reactions: [
      { equation: '2H2 + O2 -> 2H2O', type: 'Combustion / Synthesis', description: 'Explosive exothermic reaction releasing energy and water.' },
      { equation: 'N2 + 3H2 -> 2NH3', type: 'Haber Process (Synthesis)', description: 'Catalytic industrial conversion of nitrogen and hydrogen into ammonia.' },
      { equation: 'Zn + 2HCl -> ZnCl2 + H2', type: 'Single Displacement', description: 'Standard laboratory preparation of hydrogen gas from metals.' }
    ],
    safety: 'Extremely flammable gas. Forms explosive mixtures with air at concentrations between 4% and 75%.'
  },
  {
    number: 2, symbol: 'He', name: 'Helium', atomicMass: 4.0026, category: 'noble-gas',
    group: 18, period: 1, block: 's', state: 'Gas',
    electronConfiguration: '1s²', electronsPerShell: [2],
    electronegativity: null, meltingPoint: 0.95, boilingPoint: 4.22, density: 0.1786,
    atomicRadius: 31, ionizationEnergy: 2372.3, electronAffinity: -48,
    oxidationStates: [0], discoveredBy: 'Pierre Janssen & Norman Lockyer', yearDiscovered: 1868,
    summary: 'Helium is a colorless, odorless, non-toxic, inert noble gas with the lowest boiling and melting points among all elements.',
    occurrence: 'Second most abundant in the cosmos; trapped beneath Earth crust in natural gas deposits via alpha decay of uranium/thorium.',
    extraction: 'Extracted through fractional cryogenic distillation of natural gas reservoirs containing up to 7% helium.',
    applications: ['Cryogenic cooling for MRI scanners and NMR spectrometers', 'Protective shielding gas for arc welding', 'Lifting gas for airships and scientific weather balloons', 'Deep-sea diving gas mixtures (Heliox)'],
    importantCompounds: [
      { formula: 'HeH+', name: 'Hydrohelium ion', use: 'Astrophysical cosmological ion; believed to be the first molecule in the universe' }
    ],
    reactions: [
      { equation: 'He + energy -> He* (metastable)', type: 'Excitation', description: 'Extremely inert; chemically inert under standard laboratory conditions.' }
    ],
    safety: 'Asphyxiant in enclosed spaces by displacement of breathable oxygen. Cryogenic liquid causes instant severe frostbite.'
  },
  {
    number: 3, symbol: 'Li', name: 'Lithium', atomicMass: 6.94, category: 'alkali-metal',
    group: 1, period: 2, block: 's', state: 'Solid',
    electronConfiguration: '[He] 2s¹', electronsPerShell: [2, 1],
    electronegativity: 0.98, meltingPoint: 453.69, boilingPoint: 1603, density: 0.534,
    atomicRadius: 167, ionizationEnergy: 520.2, electronAffinity: 59.6,
    oxidationStates: [1], discoveredBy: 'Johan August Arfwedson', yearDiscovered: 1817,
    summary: 'Lithium is the least dense solid element, a soft silvery-white alkali metal with remarkable electrochemical potential.',
    occurrence: 'Found in granitic pegmatites (spodumene) and continental salt brine lakes (salars).',
    extraction: 'Evaporative concentration from salt brines followed by soda ash precipitation, or acid roasting of spodumene ore.',
    applications: ['Rechargeable lithium-ion batteries for EVs and electronics', 'Mood-stabilizing psychiatric medicine', 'High-temperature lubricating greases', 'Lightweight aluminum-lithium aerospace alloys'],
    importantCompounds: [
      { formula: 'Li2CO3', name: 'Lithium Carbonate', use: 'Precursor for cathode materials and psychiatric medication' },
      { formula: 'LiOH', name: 'Lithium Hydroxide', use: 'CO2 scrubbing in spacecraft and submarine air purification' },
      { formula: 'LiCoO2', name: 'Lithium Cobalt Oxide', use: 'Common cathode material for portable electronics' }
    ],
    reactions: [
      { equation: '2Li + 2H2O -> 2LiOH + H2', type: 'Redox / Displacement', description: 'Vigorous reaction with water forming basic lithium hydroxide and hydrogen gas.' },
      { equation: '4Li + O2 -> 2Li2O', type: 'Combustion / Synthesis', description: 'Forms lithium oxide with a brilliant crimson-red flame.' }
    ],
    safety: 'Reacts corrosively with moisture on skin. Water-reactive; store under mineral oil or dry argon.'
  },
  {
    number: 4, symbol: 'Be', name: 'Beryllium', atomicMass: 9.0122, category: 'alkaline-earth',
    group: 2, period: 2, block: 's', state: 'Solid',
    electronConfiguration: '[He] 2s²', electronsPerShell: [2, 2],
    electronegativity: 1.57, meltingPoint: 1560, boilingPoint: 2742, density: 1.85,
    atomicRadius: 112, ionizationEnergy: 899.5, electronAffinity: -50,
    oxidationStates: [2], discoveredBy: 'Louis-Nicolas Vauquelin', yearDiscovered: 1798,
    summary: 'Beryllium is a relatively rare, steel-gray, lightweight metal known for high stiffness, high thermal conductivity, and X-ray transparency.',
    occurrence: 'Naturally occurs in beryl mineral deposits, emeralds, and bertrandite.',
    extraction: 'Extraction via sintering with sodium fluorosilicate followed by magnesium reduction of beryllium fluoride.',
    applications: ['Aerospace mirrors (James Webb Space Telescope)', 'Beryllium-copper non-sparking safety tools', 'X-ray tube transmission windows', 'Neutron reflectors in nuclear reactors'],
    importantCompounds: [
      { formula: 'BeO', name: 'Beryllium Oxide', use: 'Thermal conductor with exceptional electrical insulation properties' },
      { formula: 'BeCl2', name: 'Beryllium Chloride', use: 'Polymerization catalyst in organic synthesis' }
    ],
    reactions: [
      { equation: '2Be + O2 -> 2BeO', type: 'Synthesis', description: 'Forms a protective passivating oxide film at elevated temperatures.' },
      { equation: 'Be + 2HCl -> BeCl2 + H2', type: 'Single Displacement', description: 'Reacts with mineral acids releasing hydrogen gas.' }
    ],
    safety: 'Highly toxic and classified as a Group 1 carcinogen. Inhalation of dust causes chronic berylliosis.'
  },
  {
    number: 5, symbol: 'B', name: 'Boron', atomicMass: 10.81, category: 'metalloid',
    group: 13, period: 2, block: 'p', state: 'Solid',
    electronConfiguration: '[He] 2s² 2p¹', electronsPerShell: [2, 3],
    electronegativity: 2.04, meltingPoint: 2349, boilingPoint: 4200, density: 2.08,
    atomicRadius: 87, ionizationEnergy: 800.6, electronAffinity: 26.7,
    oxidationStates: [1, 2, 3], discoveredBy: 'Joseph Louis Gay-Lussac & Louis Jacques Thénard', yearDiscovered: 1808,
    summary: 'Boron is a versatile metalloid that bridges metals and nonmetals, forming complex electron-deficient cluster molecules and boranes.',
    occurrence: 'Precipitated in evaporite beds as borax, kernite, colemanite, and ulexite.',
    extraction: 'Processed from mined borate ores using sulfuric acid to yield boric acid, reduced with magnesium or zinc.',
    applications: ['Borosilicate thermal shock-resistant glassware (Pyrex)', 'Fiberglass insulation', 'Semiconductor p-type dopant', 'Control rods in nuclear reactors'],
    importantCompounds: [
      { formula: 'H3BO3', name: 'Boric Acid', use: 'Antiseptic, insecticide, and nuclear flux moderator' },
      { formula: 'Na2B4O7*10H2O', name: 'Borax', use: 'Detergent booster, metallurgical flux, and ceramic glaze' },
      { formula: 'BN', name: 'Boron Nitride', use: 'High-temperature solid lubricant and ultra-hard abrasive' }
    ],
    reactions: [
      { equation: '4B + 3O2 -> 2B2O3', type: 'Combustion', description: 'Burns at high temperature with a distinct green flame to form diboron trioxide.' },
      { equation: '2B + 3Cl2 -> 2BCl3', type: 'Halogenation', description: 'Reacts with chlorine gas producing liquid boron trichloride.' }
    ],
    safety: 'Elemental boron is generally non-toxic, but high doses of borates can impair reproductive health.'
  },
  {
    number: 6, symbol: 'C', name: 'Carbon', atomicMass: 12.011, category: 'reactive-nonmetal',
    group: 14, period: 2, block: 'p', state: 'Solid',
    electronConfiguration: '[He] 2s² 2p²', electronsPerShell: [2, 4],
    electronegativity: 2.55, meltingPoint: 3823, boilingPoint: 4098, density: 2.267,
    atomicRadius: 67, ionizationEnergy: 1086.5, electronAffinity: 121.9,
    oxidationStates: [-4, -3, -2, -1, 0, 1, 2, 3, 4], discoveredBy: 'Known since antiquity', yearDiscovered: 'Ancient',
    summary: 'Carbon is the chemical basis of all known biological life due to its unparalleled ability to form stable catenated covalent chains and rings.',
    occurrence: 'Ubiquitous in fossil fuels, limestone, atmospheric CO2, and organic biomolecules.',
    extraction: 'Mined as coal and graphite; high-pressure high-temperature synthesis for industrial diamonds; thermal cracking for carbon black.',
    applications: ['Steel manufacturing (coke)', 'Carbon fiber composite materials', 'Pharmaceutical and petrochemical base', 'Lithium battery anode graphite'],
    importantCompounds: [
      { formula: 'CO2', name: 'Carbon Dioxide', use: 'Plant photosynthesis, refrigerant, carbonation' },
      { formula: 'CH4', name: 'Methane', use: 'Natural gas heating fuel and chemical feedstock' },
      { formula: 'C6H12O6', name: 'Glucose', use: 'Primary cellular energy currency in living organisms' }
    ],
    reactions: [
      { equation: 'C + O2 -> CO2', type: 'Combustion', description: 'Fundamental exothermic combustion reaction driving global energy.' },
      { equation: 'C + H2O -> CO + H2', type: 'Water-Gas Shift Precursor', description: 'High-temperature reaction producing synthesis gas (syngas).' }
    ],
    safety: 'Elemental carbon is largely inert and non-toxic. Incomplete combustion product carbon monoxide (CO) is a deadly asphyxiant.'
  },
  {
    number: 7, symbol: 'N', name: 'Nitrogen', atomicMass: 14.007, category: 'reactive-nonmetal',
    group: 15, period: 2, block: 'p', state: 'Gas',
    electronConfiguration: '[He] 2s² 2p³', electronsPerShell: [2, 5],
    electronegativity: 3.04, meltingPoint: 63.15, boilingPoint: 77.36, density: 1.2506,
    atomicRadius: 56, ionizationEnergy: 1402.3, electronAffinity: -6.8,
    oxidationStates: [-3, -2, -1, 1, 2, 3, 4, 5], discoveredBy: 'Daniel Rutherford', yearDiscovered: 1772,
    summary: 'Nitrogen is a diatomic gas making up 78% of Earth atmosphere, bonded by an exceptionally strong covalent triple bond (N≡N).',
    occurrence: 'Atmospheric air (78.08% by volume), nitrate mineral deposits (caliche), proteins, and nucleic acids.',
    extraction: 'Fractional cryogenic distillation of liquified atmospheric air.',
    applications: ['Agricultural synthetic fertilizers', 'Inert purging atmosphere in food packing and electronics', 'Cryogenic freezing with liquid nitrogen', 'Explosives and pharmaceutical intermediates'],
    importantCompounds: [
      { formula: 'NH3', name: 'Ammonia', use: 'Synthetic nitrogen fertilizer precursor' },
      { formula: 'HNO3', name: 'Nitric Acid', use: 'Fertilizers, explosives, and metal etching' },
      { formula: 'N2O', name: 'Nitrous Oxide', use: 'Dental anesthetic (laughing gas) and rocket oxidizer' }
    ],
    reactions: [
      { equation: 'N2 + 3H2 -> 2NH3', type: 'Haber-Bosch Synthesis', description: 'High pressure (150-250 atm) and catalyst (Fe) reaction essential to world food supply.' },
      { equation: 'N2 + O2 -> 2NO', type: 'Thermal Fixation', description: 'Endothermic reaction occurring during lightning strikes and combustion engines.' }
    ],
    safety: 'Liquid nitrogen causes rapid cryogenic frostbite. Asphyxiation hazard in confined unventilated spaces.'
  },
  {
    number: 8, symbol: 'O', name: 'Oxygen', atomicMass: 15.999, category: 'reactive-nonmetal',
    group: 16, period: 2, block: 'p', state: 'Gas',
    electronConfiguration: '[He] 2s² 2p⁴', electronsPerShell: [2, 6],
    electronegativity: 3.44, meltingPoint: 54.36, boilingPoint: 90.20, density: 1.429,
    atomicRadius: 48, ionizationEnergy: 1313.9, electronAffinity: 141.0,
    oxidationStates: [-2, -1, 1, 2], discoveredBy: 'Carl Wilhelm Scheele & Joseph Priestley', yearDiscovered: 1774,
    summary: 'Oxygen is a highly reactive electronegative nonmetal that supports aerobic cellular respiration and acts as the universal oxidizing agent.',
    occurrence: 'Most abundant element in Earth crust (~46% by mass) and constitutes 20.95% of atmospheric volume.',
    extraction: 'Fractional distillation of liquified air or electrolysis of acidified water.',
    applications: ['Steelmaking and basic oxygen furnaces', 'Medical oxygen therapy in hospitals', 'Rocket propellant liquid oxidizer (LOX)', 'Wastewater aerobic treatment and ozone sterilization'],
    importantCompounds: [
      { formula: 'H2O', name: 'Water', use: 'Universal solvent and primary constituent of Earth hydrosphere' },
      { formula: 'O3', name: 'Ozone', use: 'Stratospheric UV shield and powerful water purifying disinfectant' },
      { formula: 'SiO2', name: 'Silicon Dioxide', use: 'Main component of sand, quartz, and electronic glass' }
    ],
    reactions: [
      { equation: 'CH4 + 2O2 -> CO2 + 2H2O', type: 'Complete Combustion', description: 'Exothermic oxidation of hydrocarbons yielding heat energy.' },
      { equation: '4Fe + 3O2 -> 2Fe2O3', type: 'Oxidation / Corrosion', description: 'Spontaneous atmospheric oxidation of iron in the presence of moisture.' }
    ],
    safety: 'Strong oxidizer that dramatically accelerates combustion of flammable materials. High-pressure oxygen poses fire risks.'
  },
  {
    number: 9, symbol: 'F', name: 'Fluorine', atomicMass: 18.998, category: 'reactive-nonmetal',
    group: 17, period: 2, block: 'p', state: 'Gas',
    electronConfiguration: '[He] 2s² 2p⁵', electronsPerShell: [2, 7],
    electronegativity: 3.98, meltingPoint: 53.53, boilingPoint: 85.03, density: 1.696,
    atomicRadius: 42, ionizationEnergy: 1681.0, electronAffinity: 328.0,
    oxidationStates: [-1], discoveredBy: 'Henri Moissan', yearDiscovered: 1886,
    summary: 'Fluorine is the most electronegative and chemically reactive of all elements, attacking glass, metals, and water aggressively.',
    occurrence: 'Abundant in minerals such as fluorite (CaF2), fluorapatite, and cryolite.',
    extraction: 'Electrolysis of anhydrous hydrogen fluoride dissolved in molten potassium bifluoride (KF*2HF).',
    applications: ['Uranium hexafluoride enrichment for nuclear energy', 'Fluoropolymer synthesis (PTFE / Teflon)', 'Dental cavity prevention additives (fluoride toothpaste)', 'Fluorinated pharmaceuticals to enhance metabolic stability'],
    importantCompounds: [
      { formula: 'HF', name: 'Hydrofluoric Acid', use: 'Etching semiconductor silicon and glass fabrication' },
      { formula: 'UF6', name: 'Uranium Hexafluoride', use: 'Gaseous isotope separation in nuclear centrifuges' },
      { formula: 'NaF', name: 'Sodium Fluoride', use: 'Dental prophylaxis and water fluoridation' }
    ],
    reactions: [
      { equation: '2F2 + 2H2O -> 4HF + O2', type: 'Redox Displacement', description: 'Fluorine oxidizes water violently, liberating oxygen and toxic HF.' },
      { equation: 'H2 + F2 -> 2HF', type: 'Synthesis', description: 'Reacts explosively even in the dark at cryogenic temperatures.' }
    ],
    safety: 'Extremely toxic and corrosive gas. Hydrofluoric acid (HF) penetrates tissue and binds calcium, causing cardiac arrest.'
  },
  {
    number: 10, symbol: 'Ne', name: 'Neon', atomicMass: 20.180, category: 'noble-gas',
    group: 18, period: 2, block: 'p', state: 'Gas',
    electronConfiguration: '[He] 2s² 2p⁶', electronsPerShell: [2, 8],
    electronegativity: null, meltingPoint: 24.56, boilingPoint: 27.07, density: 0.9002,
    atomicRadius: 38, ionizationEnergy: 2080.7, electronAffinity: -116,
    oxidationStates: [0], discoveredBy: 'William Ramsay & Morris Travers', yearDiscovered: 1898,
    summary: 'Neon is a colorless, odorless noble gas that glows with a brilliant reddish-orange discharge in high-voltage electrical fields.',
    occurrence: 'Trace atmospheric constituent (~18.18 ppm); abundant cosmically in stellar atmospheres.',
    extraction: 'Obtained as a non-condensable byproduct from the cryogenic distillation of liquid air.',
    applications: ['Luminous advertising neon signage', 'Helium-neon gas lasers (HeNe lasers) for surveying and barcodes', 'Cryogenic refrigeration in specialized sensor cooling', 'High-voltage indicator lights and surge arrestors'],
    importantCompounds: [
      { formula: 'Ne', name: 'Elemental Neon', use: 'Does not form stable neutral chemical compounds under standard conditions' }
    ],
    reactions: [
      { equation: 'Ne + e- (high voltage) -> Ne* + e- -> Ne + photon (632.8 nm)', type: 'Luminescence', description: 'Electrical discharge excites valence electrons, emitting characteristic orange-red photons.' }
    ],
    safety: 'Non-toxic, chemically inert gas. Can cause asphyxiation if it displaces breathable oxygen.'
  }
];

// Helper master array that covers elements 11-118 with concise verified parameters and expands them
const baseData = [
  // 11-20
  [11, 'Na', 'Sodium', 22.990, 'alkali-metal', 1, 3, 's', 'Solid', '[Ne] 3s¹', [2,8,1], 0.93, 370.87, 1156, 0.968, 190, 495.8, 52.8, [1], 'Humphry Davy', 1807, 'Soft silvery reactive alkali metal essential as an extracellular electrolyte.', 'Halite rock salt deposits and oceans.', 'Downs cell electrolysis of molten NaCl.', ['Food seasoning and preservation (NaCl)', 'Fast neutron reactor liquid cooling', 'Street vapor lamps'], [{f:'NaCl',n:'Sodium Chloride',u:'Universal table salt'},{f:'NaOH',n:'Sodium Hydroxide',u:'Caustic soda'}], [{eq:'2Na + 2H2O -> 2NaOH + H2',t:'Displacement',d:'Vigorous exothermic reaction.'}], 'Water-reactive; causes severe alkali chemical burns.'],
  [12, 'Mg', 'Magnesium', 24.305, 'alkaline-earth', 2, 3, 's', 'Solid', '[Ne] 3s²', [2,8,2], 1.31, 923, 1363, 1.738, 145, 737.7, -40, [2], 'Joseph Black', 1755, 'Lightweight alkaline-earth metal essential in chlorophyll photosynthesis.', 'Dolomite, magnesite, and seawater.', 'Electrolysis of molten MgCl2 or Pidgeon process.', ['Aerospace and automotive lightweight alloys', 'Grignard organic reagents', 'Emergency flares'], [{f:'MgO',n:'Magnesium Oxide',u:'Refractory furnace lining'},{f:'MgSO4',n:'Epsom Salt',u:'Therapeutic mineral'}], [{eq:'2Mg + O2 -> 2MgO',t:'Combustion',d:'Blinding bright white flame.'}], 'Magnesium ribbon/powder burns with intense light and heat.'],
  [13, 'Al', 'Aluminium', 26.982, 'post-transition-metal', 13, 3, 'p', 'Solid', '[Ne] 3s² 3p¹', [2,8,3], 1.61, 933.47, 2743, 2.70, 118, 577.5, 42.5, [3], 'Hans Christian Ørsted', 1825, 'Most abundant metal in Earth crust, lightweight with a passivating oxide barrier.', 'Bauxite ore.', 'Bayer process followed by Hall-Héroult molten electrolysis.', ['Aircraft fuselage, car frames, and trains', 'Beverage cans and foil wrap', 'Overhead electric transmission cables'], [{f:'Al2O3',n:'Alumina',u:'Abrasives and synthetic rubies'},{f:'AlCl3',n:'Aluminium Chloride',u:'Friedel-Crafts catalyst'}], [{eq:'2Al + Fe2O3 -> Al2O3 + 2Fe',t:'Thermite Reaction',d:'Molten iron railroad welding.'}], 'Finely divided aluminium powder presents dust explosion hazard.'],
  [14, 'Si', 'Silicon', 28.085, 'metalloid', 14, 3, 'p', 'Solid', '[Ne] 3s² 3p²', [2,8,4], 1.90, 1687, 3538, 2.329, 111, 786.5, 134.1, [-4,2,4], 'Jöns Jacob Berzelius', 1824, 'Semiconductor metalloid forming the foundation of modern computers and solar panels.', 'Silica quartz sand and silicates.', 'Carbothermic reduction of quartz followed by Siemens process.', ['Computer microprocessors and memory chips', 'Photovoltaic solar panels', 'Silicone sealants and polymers'], [{f:'SiO2',n:'Silica',u:'Window glass and concrete'},{f:'SiC',n:'Carborundum',u:'Abrasive and high-voltage power chips'}], [{eq:'SiO2 + 2C -> Si + 2CO',t:'Carbothermic Reduction',d:'Arc furnace smelting of quartz.'}], 'Inhaled silica dust causes chronic irreversible pulmonary silicosis.'],
  [15, 'P', 'Phosphorus', 30.974, 'reactive-nonmetal', 15, 3, 'p', 'Solid', '[Ne] 3s² 3p³', [2,8,5], 2.19, 317.30, 553.65, 1.823, 98, 1011.8, 72.0, [-3,3,5], 'Hennig Brand', 1669, 'Multivalent nonmetal forming the phosphate backbone of DNA, RNA, and ATP energy.', 'Sedimentary phosphorite rock.', 'Thermal arc furnace reduction with coke and silica.', ['Agricultural synthetic fertilizers', 'Safety match striker friction strips', 'Flame retardant additives'], [{f:'H3PO4',n:'Phosphoric Acid',u:'Beverage acidulant and rust remover'},{f:'P4O10',n:'Phosphorus Pentoxide',u:'Powerful dehydrating agent'}], [{eq:'P4 + 5O2 -> P4O10',t:'Combustion',d:'White phosphorus burns spontaneously in air.'}], 'White phosphorus is pyrophoric and inflicts deep severe chemical burns.'],
  [16, 'S', 'Sulfur', 32.06, 'reactive-nonmetal', 16, 3, 'p', 'Solid', '[Ne] 3s² 3p⁴', [2,8,6], 2.58, 388.36, 717.8, 2.07, 88, 999.6, 200.4, [-2,2,4,6], 'Known since antiquity', 'Ancient', 'Vibrant yellow nonmetal forming S8 rings, historically known as brimstone.', 'Volcanic deposits and sour natural gas.', 'Claus catalytic process from hydrogen sulfide.', ['Sulfuric acid manufacturing (world #1 chemical)', 'Rubber tire vulcanization', 'Fungicides and agricultural soil conditioners'], [{f:'H2SO4',n:'Sulfuric Acid',u:'Industrial chemical processing'},{f:'SO2',n:'Sulfur Dioxide',u:'Wine preservative and bleaching'}], [{eq:'S + O2 -> SO2',t:'Combustion',d:'Burns with a blue flame.'}], 'Non-toxic element; byproduct SO2 gas is choking and toxic.'],
  [17, 'Cl', 'Chlorine', 35.45, 'reactive-nonmetal', 17, 3, 'p', 'Gas', '[Ne] 3s² 3p⁵', [2,8,7], 3.16, 171.6, 239.11, 3.2, 79, 1251.2, 349.0, [-1,1,3,5,7], 'Carl Wilhelm Scheele', 1774, 'Pungent greenish-yellow halogen gas essential for water disinfection and PVC.', 'Oceanic chloride salts and halite.', 'Chlor-alkali electrolysis of aqueous NaCl brine.', ['Drinking water purification and swimming pool chlorination', 'PVC construction plastic piping', 'Pharmaceutical chemical synthesis'], [{f:'NaCl',n:'Sodium Chloride',u:'Salt'},{f:'NaClO',n:'Sodium Hypochlorite',u:'Disinfectant bleach'}], [{eq:'Cl2 + H2O -> HCl + HClO',t:'Disproportionation',d:'Forms sterilizing hypochlorous acid.'}], 'Toxic corrosive choking gas; causes pulmonary damage upon inhalation.'],
  [18, 'Ar', 'Argon', 39.95, 'noble-gas', 18, 3, 'p', 'Gas', '[Ne] 3s² 3p⁶', [2,8,8], null, 83.81, 87.30, 1.784, 71, 1520.6, -96, [0], 'Lord Rayleigh & William Ramsay', 1894, 'Inert atmospheric noble gas (0.93%) used as a non-reactive protective shielding envelope.', 'Earth atmosphere.', 'Fractional distillation of liquid air.', ['Inert shielding gas for TIG and MIG welding', 'Filling incandescent light bulbs and double glazing', 'Silicon crystal fabrication atmosphere'], [{f:'HArF',n:'Argon Fluorohydride',u:'Low-temperature theoretical compound'}], [{eq:'Ar + heat -> Ar (inert)',t:'Thermal Stability',d:'Chemically inert.'}], 'Non-toxic; risk of asphyxiation in enclosed unventilated areas.'],
  [19, 'K', 'Potassium', 39.098, 'alkali-metal', 1, 4, 's', 'Solid', '[Ar] 4s¹', [2,8,8,1], 0.82, 336.53, 1032, 0.862, 220, 418.8, 48.4, [1], 'Humphry Davy', 1807, 'Soft silvery alkali metal acting as the major intracellular cation in human neurons.', 'Sylvite (KCl) and potash deposits.', 'Sodium vapor reduction of molten KCl at 850°C.', ['Agricultural potash fertilizers', 'Specialty liquid soap manufacturing', 'Gorilla Glass chemical strengthening'], [{f:'KCl',n:'Potassium Chloride',u:'Potash fertilizer'},{f:'KNO3',n:'Saltpeter',u:'Pyrotechnics and tree stump remover'}], [{eq:'2K + 2H2O -> 2KOH + H2',t:'Explosive Displacement',d:'Lilac flame explosion upon water contact.'}], 'Violently water-reactive; causes severe skin burns.'],
  [20, 'Ca', 'Calcium', 40.078, 'alkaline-earth', 2, 4, 's', 'Solid', '[Ar] 4s²', [2,8,8,2], 1.00, 1115, 1757, 1.55, 180, 589.8, 2.37, [2], 'Humphry Davy', 1808, 'Abundant alkaline-earth metal essential for bones, teeth, and building cements.', 'Limestone, chalk, marble, and gypsum.', 'Aluminothermic reduction of lime or electrolysis of molten CaCl2.', ['Portland cement and concrete construction', 'Metallurgical reducing agent for rare metals', 'Dietary calcium bone health supplements'], [{f:'CaCO3',n:'Calcium Carbonate',u:'Limestone rock and antacid'},{f:'CaO',n:'Quicklime',u:'Steel flux and mortar'}], [{eq:'CaCO3 -> CaO + CO2',t:'Calcination',d:'Thermal decomposition of limestone.'}], 'Reacts with water to generate caustic lime and heat.'],

  // 21-30
  [21, 'Sc', 'Scandium', 44.956, 'transition-metal', 3, 4, 'd', 'Solid', '[Ar] 3d¹ 4s²', [2,8,9,2], 1.36, 1814, 3109, 2.985, 144, 633.1, 18, [3], 'Lars Fredrik Nilson', 1879, 'Lightweight transition metal strengthening aluminium aerospace alloys.', 'Thortveitite and bauxite residue.', 'Solvent extraction from uranium/bauxite processing.', ['Aluminium-scandium aircraft airframes', 'High-intensity metal halide stadium lamps', 'Solid oxide fuel cells'], [{f:'Sc2O3',n:'Scandia',u:'Laser crystal dopant'}], [{eq:'4Sc + 3O2 -> 2Sc2O3',t:'Oxidation',d:'Forms scandia oxide.'}], 'Low toxicity metal; handle powder with dust precautions.'],
  [22, 'Ti', 'Titanium', 47.867, 'transition-metal', 4, 4, 'd', 'Solid', '[Ar] 3d² 4s²', [2,8,10,2], 1.54, 1941, 3560, 4.506, 132, 658.8, 7.6, [2,3,4], 'William Gregor', 1791, 'Highest strength-to-weight ratio metal, biocompatible and intensely corrosion-resistant.', 'Ilmenite and rutile sand.', 'Kroll process: TiCl4 reduction with magnesium.', ['Jet aircraft engines and supersonic airframes', 'Biocompatible orthopedic bone implants', 'White pigment (TiO2) in paints'], [{f:'TiO2',n:'Titanium Dioxide',u:'Premier opaque white pigment'},{f:'TiCl4',n:'Titanium Tetrachloride',u:'Ziegler-Natta catalyst'}], [{eq:'TiCl4 + 2Mg -> Ti + 2MgCl2',t:'Kroll Reduction',d:'Produces titanium metal sponge.'}], 'Biocompatible; fine titanium powder is pyrophoric.'],
  [23, 'V', 'Vanadium', 50.942, 'transition-metal', 5, 4, 'd', 'Solid', '[Ar] 3d³ 4s²', [2,8,11,2], 1.63, 2183, 3680, 6.11, 122, 650.9, 50.6, [2,3,4,5], 'Andrés Manuel del Río', 1801, 'Hard ductile transition metal famous for four vibrant oxidation state colors.', 'Titanomagnetite iron ores and petroleum soot.', 'Roasting titanomagnetite slag with sodium carbonate.', ['High-strength structural tool steel', 'Vanadium redox flow batteries (VRFB)', 'Sulfuric acid catalyst (V2O5)'], [{f:'V2O5',n:'Vanadium Pentoxide',u:'Contact process catalyst'}], [{eq:'2SO2 + O2 --(V2O5)--> 2SO3',t:'Catalytic Oxidation',d:'Oxidation of sulfur dioxide.'}], 'Vanadium oxide dust is toxic and irritating to lungs.'],
  [24, 'Cr', 'Chromium', 51.996, 'transition-metal', 6, 4, 'd', 'Solid', '[Ar] 3d⁵ 4s¹', [2,8,13,1], 1.66, 2180, 2944, 7.19, 118, 652.9, 64.3, [2,3,6], 'Louis-Nicolas Vauquelin', 1797, 'Steel-gray hard metal imparting rust-proof passivation to stainless steel.', 'Chromite ore (FeCr2O4).', 'Smelting chromite with carbon yields ferrochrome.', ['Stainless steel formulation (min 10.5% Cr)', 'Decorative chrome electroplating', 'Leather tanning salts'], [{f:'Cr2O3',n:'Chromium(III) Oxide',u:'Green ceramic pigment'},{f:'K2Cr2O7',n:'Potassium Dichromate',u:'Oxidizing agent'}], [{eq:'4Cr + 3O2 -> 2Cr2O3',t:'Passivation',d:'Tenacious rust-preventing film.'}], 'Trivalent Cr(III) is safe; hexavalent Cr(VI) is a recognized carcinogen.'],
  [25, 'Mn', 'Manganese', 54.938, 'transition-metal', 7, 4, 'd', 'Solid', '[Ar] 3d⁵ 4s²', [2,8,13,2], 1.55, 1519, 2334, 7.21, 117, 717.3, 0, [2,3,4,6,7], 'Johan Gottlieb Gahn', 1774, 'Hard brittle metal essential for desulfurizing and strengthening all carbon steel.', 'Pyrolusite (MnO2) and deep-sea nodules.', 'Blast furnace smelting to ferromanganese.', ['Steel deoxidation and alloying', 'NMC lithium EV battery cathodes', 'Alkaline battery depolarizers'], [{f:'MnO2',n:'Manganese Dioxide',u:'Battery cathode and oxidant'},{f:'KMnO4',n:'Potassium Permanganate',u:'Purple antiseptic'}], [{eq:'2KMnO4 + 16HCl -> 2KCl + 2MnCl2 + 5Cl2 + 8H2O',t:'Redox',d:'Chlorine gas generation.'}], 'Chronic inhalation causes neurological manganism.'],
  [26, 'Fe', 'Iron', 55.845, 'transition-metal', 8, 4, 'd', 'Solid', '[Ar] 3d⁶ 4s²', [2,8,14,2], 1.83, 1811, 3134, 7.874, 117, 762.5, 15.7, [2,3], 'Known since antiquity', 'Ancient', 'Most used metal on Earth, backbone of structural steel and blood hemoglobin.', 'Hematite and magnetite iron ores.', 'Blast furnace reduction using coke and limestone.', ['Structural steel for construction and transport', 'Cast iron automotive machinery', 'Ammonia Haber catalyst'], [{f:'Fe2O3',n:'Iron(III) Oxide',u:'Rust and pigment'},{f:'FeSO4',n:'Iron(II) Sulfate',u:'Nutritional iron supplement'}], [{eq:'Fe2O3 + 3CO -> 2Fe + 3CO2',t:'Reduction',d:'Blast furnace extraction.'}], 'Non-toxic in bulk metal; massive oral overdose in children is toxic.'],
  [27, 'Co', 'Cobalt', 58.933, 'transition-metal', 9, 4, 'd', 'Solid', '[Ar] 3d⁷ 4s²', [2,8,15,2], 1.88, 1768, 3200, 8.90, 116, 760.4, 63.7, [2,3], 'Georg Brandt', 1735, 'Ferromagnetic blue-tinted metal critical for superalloys and EV battery cathodes.', 'Byproduct of copper and nickel ores.', 'Acid leaching followed by electrowinning.', ['Lithium-ion EV batteries (NMC and LCO)', 'Jet turbine engine superalloys', 'Cobalt-60 cancer radiation therapy'], [{f:'Co3O4',n:'Cobalt Oxide',u:'Battery cathode synthesis'},{f:'CoCl2',n:'Cobalt Chloride',u:'Humidity test strips'}], [{eq:'CoCl2*6H2O <-> CoCl2 + 6H2O',t:'Hydration',d:'Reversible pink-to-blue color change.'}], 'Cobalt dust is an allergen and potential carcinogen.'],
  [28, 'Ni', 'Nickel', 58.693, 'transition-metal', 10, 4, 'd', 'Solid', '[Ar] 3d⁸ 4s²', [2,8,16,2], 1.91, 1728, 3003, 8.908, 115, 737.1, 112.0, [2,3], 'Axel Fredrik Cronstedt', 1751, 'Ductile corrosion-resistant metal essential for austenitic stainless steel.', 'Laterites and pentlandite sulfide ores.', 'Mond process using volatile nickel carbonyl.', ['Stainless steel alloying', 'EV battery chemistry (NMC)', 'Raney nickel organic hydrogenation catalyst'], [{f:'NiO',n:'Nickel Oxide',u:'Ceramic glazes and cathodes'},{f:'Ni(CO)4',n:'Nickel Tetracarbonyl',u:'Volatile refining intermediate'}], [{eq:'Ni + 4CO -> Ni(CO)4',t:'Carbonylation',d:'Mond refining step.'}], 'Common skin allergen; nickel carbonyl gas is deadly toxic.'],
  [29, 'Cu', 'Copper', 63.546, 'transition-metal', 11, 4, 'd', 'Solid', '[Ar] 3d¹⁰ 4s¹', [2,8,18,1], 1.90, 1357.77, 2835, 8.96, 117, 745.5, 118.4, [1,2], 'Known since antiquity', 'Ancient', 'Reddish-orange metal with supreme electrical and thermal conductivity.', 'Chalcopyrite and malachite copper ores.', 'Froth flotation, smelting, and electrolytic refining.', ['Electrical wiring, electric motors, and grid cables', 'Plumbing pipework and heat exchangers', 'Brass and bronze traditional alloys'], [{f:'CuSO4',n:'Copper Sulfate',u:'Agricultural fungicide'},{f:'CuO',n:'Copper Oxide',u:'Superconductor research'}], [{eq:'Cu + 4HNO3 -> Cu(NO3)2 + 2NO2 + 2H2O',t:'Dissolution',d:'Releases dense brown NO2 gas.'}], 'Low human toxicity; highly toxic to aquatic organisms.'],
  [30, 'Zn', 'Zinc', 65.38, 'transition-metal', 12, 4, 'd', 'Solid', '[Ar] 3d¹⁰ 4s²', [2,8,18,2], 1.65, 692.68, 1180, 7.14, 125, 906.4, -58, [2], 'Andreas Sigismund Marggraf', 1746, 'Bluish-white metal used extensively as sacrificial galvanized rust protection.', 'Sphalerite zinc sulfide ore.', 'Roasting to ZnO followed by electrowinning.', ['Hot-dip galvanizing of construction steel', 'Die-casting precision components (Zamak)', 'Nutritional immune support and sunscreen (ZnO)'], [{f:'ZnO',n:'Zinc Oxide',u:'Mineral sunscreen UV filter'},{f:'ZnSO4',n:'Zinc Sulfate',u:'Dietary supplement'}], [{eq:'Zn + 2HCl -> ZnCl2 + H2',t:'Displacement',d:'Generates hydrogen gas.'}], 'Welding zinc fumes can cause temporary metal fume fever.'],

  // 31-36 (Gallium to Krypton)
  [31, 'Ga', 'Gallium', 69.723, 'post-transition-metal', 13, 4, 'p', 'Solid', '[Ar] 3d¹⁰ 4s² 4p¹', [2,8,18,3], 1.81, 302.91, 2673, 5.91, 126, 578.8, 28.9, [3], 'Paul-Émile Lecoq de Boisbaudran', 1875, 'Melts in the hand (29.76°C) and powers modern high-speed semiconductors.', 'Trace byproduct in bauxite.', 'Electrolysis of Bayer process liquors.', ['Gallium nitride (GaN) fast chargers and blue LEDs', 'Gallium arsenide (GaAs) RF microwave chips', 'Liquid metal thermal paste'], [{f:'GaAs',n:'Gallium Arsenide',u:'High-efficiency solar cells and radar'}], [{eq:'4Ga + 3O2 -> 2Ga2O3',t:'Oxidation',d:'Forms oxide layer.'}], 'Liquid gallium severely embrittles solid aluminium metal.'],
  [32, 'Ge', 'Germanium', 72.630, 'metalloid', 14, 4, 'p', 'Solid', '[Ar] 3d¹⁰ 4s² 4p²', [2,8,18,4], 2.01, 1211.40, 3106, 5.323, 122, 762.0, 119.0, [2,4], 'Clemens Winkler', 1886, 'Lustrous gray metalloid historically used in the first transistors.', 'Zinc sphalerite flue dusts.', 'Chlorination to GeCl4 followed by hydrolysis.', ['Fiber optic core dopant to boost refraction', 'Infrared thermal imaging lenses', 'Polymerization catalyst for PET plastic'], [{f:'GeO2',n:'Germanium Dioxide',u:'Optical fiber dopant'}], [{eq:'Ge + O2 -> GeO2',t:'Oxidation',d:'High-temperature oxidation.'}], 'Low toxicity in elemental state.'],
  [33, 'As', 'Arsenic', 74.922, 'metalloid', 15, 4, 'p', 'Solid', '[Ar] 3d¹⁰ 4s² 4p³', [2,8,18,5], 2.18, 1090, 887, 5.727, 119, 947.0, 78.0, [-3,3,5], 'Albertus Magnus', 1250, 'Notorious toxic metalloid sublimating at 614°C, used in compound semiconductors.', 'Arsenopyrite mineral veins.', 'Roasting arsenopyrite in air.', ['GaAs high-frequency semiconductor wafers', 'Lead-acid car battery hardener', 'Leukemia chemotherapy (arsenic trioxide)'], [{f:'As2O3',n:'Arsenic Trioxide',u:'Acute promyelocytic leukemia drug'}], [{eq:'4As + 3O2 -> 2As2O3',t:'Combustion',d:'Garlic-scented toxic fumes.'}], 'Extremely potent poison and human carcinogen.'],
  [34, 'Se', 'Selenium', 78.971, 'reactive-nonmetal', 16, 4, 'p', 'Solid', '[Ar] 3d¹⁰ 4s² 4p⁴', [2,8,18,6], 2.55, 494, 958, 4.81, 120, 941.0, 195.0, [-2,2,4,6], 'Jöns Jacob Berzelius', 1817, 'Photoconductive nonmetal whose conductivity rises 1000-fold under illumination.', 'Copper anode slimes.', 'Roasting copper refinery slimes.', ['Photocopier xerography drums', 'Ruby red colored glass manufacturing', 'CIGS solar panels and dandruff shampoos'], [{f:'SeS2',n:'Selenium Disulfide',u:'Antidandruff shampoo agent'}], [{eq:'Se + O2 -> SeO2',t:'Combustion',d:'Burns with a blue flame.'}], 'Essential trace mineral; toxic in excess (selenosis).'],
  [35, 'Br', 'Bromine', 79.904, 'reactive-nonmetal', 17, 4, 'p', 'Liquid', '[Ar] 3d¹⁰ 4s² 4p⁵', [2,8,18,7], 2.96, 265.8, 332.0, 3.1028, 120, 1139.9, 324.6, [-1,1,3,5], 'Antoine Jérôme Balard', 1826, 'Only nonmetallic liquid element at room temp, fuming dense reddish-brown vapor.', 'Saline brines and the Dead Sea.', 'Chlorine displacement of bromide brine.', ['Brominated flame retardants in plastics', 'Offshore well completion fluids', 'Pharmaceutical chemical synthesis'], [{f:'AgBr',n:'Silver Bromide',u:'Photographic film emulsion'}], [{eq:'2Br- + Cl2 -> Br2 + 2Cl-',t:'Halogen Displacement',d:'Displaces liquid bromine.'}], 'Corrosive fuming liquid inflicting agonizing chemical burns.'],
  [36, 'Kr', 'Krypton', 83.798, 'noble-gas', 18, 4, 'p', 'Gas', '[Ar] 3d¹⁰ 4s² 4p⁶', [2,8,18,8], 3.00, 115.79, 119.93, 3.749, 88, 1350.8, -96, [2], 'William Ramsay & Morris Travers', 1898, 'Dense noble gas historically used to define the international standard meter.', 'Atmospheric trace gas.', 'Cryogenic liquid air distillation.', ['Insulated window thermal barrier gas', 'Excimer laser photolithography for chips (248 nm)', 'Airport runway strobe flashlamps'], [{f:'KrF2',n:'Krypton Difluoride',u:'Fluorinating oxidizer'}], [{eq:'Kr + F2 -> KrF2',t:'UV Synthesis',d:'Forms low-temp fluoride.'}], 'Asphyxiant noble gas in confined areas.'],

  // 37-54 (Period 5)
  [37, 'Rb', 'Rubidium', 85.468, 'alkali-metal', 1, 5, 's', 'Solid', '[Kr] 5s¹', [2,8,18,8,1], 0.82, 312.46, 961, 1.532, 235, 403.0, 46.9, [1], 'Robert Bunsen & Gustav Kirchhoff', 1861, 'Soft reactive alkali metal that ignites spontaneously in air.', 'Lepidolite and pollucite ores.', 'Byproduct of lithium extraction.', ['Rubidium atomic GPS frequency clocks', 'Vapor magnetometers', 'Photocathodes'], [{f:'RbCl',n:'Rubidium Chloride',u:'Biomarker'}], [{eq:'2Rb + 2H2O -> 2RbOH + H2',t:'Explosion',d:'Explosive reaction.'}], 'Pyrophoric water-reactive metal.'],
  [38, 'Sr', 'Strontium', 87.62, 'alkaline-earth', 2, 5, 's', 'Solid', '[Kr] 5s²', [2,8,18,8,2], 0.95, 1050, 1655, 2.64, 200, 549.5, 5.0, [2], 'Adair Crawford', 1790, 'Alkaline earth metal renowned for brilliant crimson pyrotechnic flares.', 'Celestite and strontianite.', 'Aluminium reduction of SrO.', ['Crimson fireworks and railway warning flares', 'Strontium-90 nuclear batteries (RTG)', 'Optical lattice atomic clocks'], [{f:'SrCO3',n:'Strontium Carbonate',u:'Red firework colorant'}], [{eq:'2Sr + O2 -> 2SrO',t:'Combustion',d:'Intense scarlet flame.'}], 'Combustible; Sr-90 isotope is a hazardous bone seeker.'],
  [39, 'Y', 'Yttrium', 88.906, 'transition-metal', 3, 5, 'd', 'Solid', '[Kr] 4d¹ 5s²', [2,8,18,9,2], 1.22, 1799, 3609, 4.472, 180, 600.0, 29.6, [3], 'Johan Gadolin', 1794, 'Silvery transition metal used in high-temp superconductors and lasers.', 'Xenotime and monazite ores.', 'Ion-exchange chromatography.', ['YBCO high-temperature superconductors', 'YAG industrial cutting lasers', 'Zirconia dental ceramics'], [{f:'Y2O3',n:'Yttria',u:'Thermal ceramic barrier'}], [{eq:'4Y + 3O2 -> 2Y2O3',t:'Oxidation',d:'Forms protective oxide.'}], 'Low toxicity metal.'],
  [40, 'Zr', 'Zirconium', 91.224, 'transition-metal', 4, 5, 'd', 'Solid', '[Kr] 4d² 5s²', [2,8,18,10,2], 1.33, 2128, 4682, 6.52, 160, 640.1, 41.1, [4], 'Martin Heinrich Klaproth', 1789, 'Corrosion-proof metal with near-zero neutron absorption for nuclear reactors.', 'Zircon mineral sands.', 'Kroll reduction of ZrCl4 with magnesium.', ['Nuclear fuel rod cladding (Zircaloy)', 'Cubic zirconia diamond substitutes', 'Chemical process equipment'], [{f:'ZrO2',n:'Zirconia',u:'High-strength ceramic'}], [{eq:'Zr + 2H2O -> ZrO2 + 2H2',t:'High-temp Oxidation',d:'Nuclear cladding reaction.'}], 'Pyrophoric in fine powder form.'],
  [41, 'Nb', 'Niobium', 92.906, 'transition-metal', 5, 5, 'd', 'Solid', '[Kr] 4d⁴ 5s¹', [2,8,18,12,1], 1.60, 2750, 5017, 8.57, 146, 652.1, 86.1, [3,5], 'Charles Hatchett', 1801, 'Ductile metal that turns rainbow hues when anodized and forms MRI superconductors.', 'Pyrochlore deposits.', 'Aluminothermic reduction of Nb2O5.', ['Superconducting MRI magnets (Nb-Ti)', 'Structural pipeline microalloyed steel', 'Jet engine nickel superalloys'], [{f:'Nb2O5',n:'Niobium Pentoxide',u:'High-index optical glass'}], [{eq:'4Nb + 5O2 -> 2Nb2O5',t:'Synthesis',d:'High-temperature oxidation.'}], 'Biocompatible hypoallergenic metal.'],
  [42, 'Mo', 'Molybdenum', 95.95, 'transition-metal', 6, 5, 'd', 'Solid', '[Kr] 4d⁵ 5s¹', [2,8,18,13,1], 2.16, 2896, 4912, 10.28, 139, 684.3, 71.9, [2,3,4,5,6], 'Carl Wilhelm Scheele', 1778, 'Refractory metal with the 6th highest melting point, essential enzyme cofactor.', 'Molybdenite ore (MoS2).', 'Roasting to MoO3 followed by hydrogen reduction.', ['High-strength steel superalloys', 'Petroleum desulfurization catalysts', 'Solid dry lubricant (MoS2)'], [{f:'MoS2',n:'Molybdenum Disulfide',u:'Solid lubricant'},{f:'99Mo',n:'Moly-99',u:'Precursor for Tc-99m'}], [{eq:'2MoS2 + 7O2 -> 2MoO3 + 4SO2',t:'Roasting',d:'Industrial roasting.'}], 'Low toxicity metal.'],
  [43, 'Tc', 'Technetium', 98.0, 'transition-metal', 7, 5, 'd', 'Solid', '[Kr] 4d⁵ 5s²', [2,8,18,13,2], 1.90, 2430, 4538, 11.5, 136, 702.0, 53.0, [4,7], 'Emilio Segrè & Carlo Perrier', 1937, 'First artificially synthesized chemical element with no stable isotopes.', 'Uranium nuclear fission byproduct.', 'Chemical extraction from irradiated nuclear fuel.', ['Technetium-99m nuclear diagnostic medical imaging scans (80% worldwide)'], [{f:'TcO4-',n:'Pertechnetate',u:'Medical radiotracer'}], [{eq:'99Mo -> 99mTc + beta',t:'Decay',d:'Medical isotope generator.'}], 'Radioactive material requiring lead shielding.'],
  [44, 'Ru', 'Ruthenium', 101.07, 'transition-metal', 8, 5, 'd', 'Solid', '[Kr] 4d⁷ 5s¹', [2,8,18,15,1], 2.20, 2607, 4423, 12.45, 134, 710.2, 101.3, [2,3,4,8], 'Karl Ernst Claus', 1844, 'Platinum group metal celebrated for chemical catalysis and hard drives.', 'Platinum group deposits.', 'Byproduct of nickel refining.', ['Hard drive magnetic recording layers', 'Grubbs olefin metathesis catalyst', 'Chlor-alkali titanium anodes'], [{f:'RuO4',n:'Ruthenium Tetroxide',u:'Volatile oxidant and stain'}], [{eq:'Ru + 2O2 -> RuO2',t:'Oxidation',d:'Conductive oxide.'}], 'RuO4 fumes are highly toxic.'],
  [45, 'Rh', 'Rhodium', 102.91, 'transition-metal', 9, 5, 'd', 'Solid', '[Kr] 4d⁸ 5s¹', [2,8,18,16,1], 2.28, 2237, 3968, 12.41, 134, 719.7, 109.7, [3], 'William Hyde Wollaston', 1804, 'Most precious noble metal, vital for automotive toxic NOx reduction.', 'Bushveld complex.', 'Precipitation from platinum refining residue.', ['Automotive catalytic converters (cleans NOx)', 'Reflective optical mirrors and jewelry plating', 'Industrial acetic acid catalysis'], [{f:'RhCl(PPh3)3',n:'Wilkinson Catalyst',u:'Hydrogenation catalyst'}], [{eq:'2NOx -> N2 + xO2',t:'Catalysis',d:'Exhaust cleansing.'}], 'Non-toxic elemental noble metal.'],
  [46, 'Pd', 'Palladium', 106.42, 'transition-metal', 10, 5, 'd', 'Solid', '[Kr] 4d¹⁰', [2,8,18,18], 2.20, 1828.05, 3236, 12.023, 137, 804.4, 53.7, [2,4], 'William Hyde Wollaston', 1803, 'Absorbs up to 900 times its volume of hydrogen gas, Nobel coupling catalyst.', 'Nickel-copper ores.', 'Solvent extraction from refinery slimes.', ['Automotive catalytic converters', 'Suzuki and Heck organic cross-coupling reactions', 'Multilayer ceramic capacitors in phones'], [{f:'PdCl2',n:'Palladium Chloride',u:'Wacker catalyst'}], [{eq:'2Pd + H2 <-> 2PdH0.5',t:'Hydrogen Sponge',d:'Reversible absorption.'}], 'Low toxicity metal.'],
  [47, 'Ag', 'Silver', 107.87, 'transition-metal', 11, 5, 'd', 'Solid', '[Kr] 4d¹⁰ 5s¹', [2,8,18,18,1], 1.93, 1234.93, 2435, 10.49, 144, 731.0, 125.6, [1], 'Known since antiquity', 'Ancient', 'Highest electrical conductivity, thermal conductivity, and optical reflectivity.', 'Native silver and argentite.', 'Parkes process and cyanide leaching.', ['Solar panel contact paste', 'Jewelry, silverware, and bullion coins', 'Antimicrobial wound dressings and catheters'], [{f:'AgNO3',n:'Silver Nitrate',u:'Antiseptic and analytical reagent'}], [{eq:'Ag+ + Cl- -> AgCl (ppt)',t:'Precipitation',d:'Curdy white precipitate.'}], 'Chronic intake causes argyria (blue skin discoloration).'],
  [48, 'Cd', 'Cadmium', 112.41, 'transition-metal', 12, 5, 'd', 'Solid', '[Kr] 4d¹⁰ 5s²', [2,8,18,18,2], 1.69, 594.22, 1040, 8.65, 151, 867.8, -68, [2], 'Friedrich Stromeyer', 1817, 'Toxic bluish metal used in thin-film solar panels and reactor control rods.', 'Zinc ores (greenockite).', 'Byproduct of zinc smelting.', ['Cadmium telluride (CdTe) utility solar panels', 'Nuclear reactor neutron control rods', 'Cadmium yellow artist pigments'], [{f:'CdTe',n:'Cadmium Telluride',u:'Solar cell semiconductor'}], [{eq:'Cd + 2HCl -> CdCl2 + H2',t:'Displacement',d:'Slow dissolution.'}], 'Highly toxic heavy metal; causes Itai-itai kidney disease.'],
  [49, 'In', 'Indium', 114.82, 'post-transition-metal', 13, 5, 'p', 'Solid', '[Kr] 4d¹⁰ 5s² 5p¹', [2,8,18,18,3], 1.78, 429.75, 2345, 7.31, 167, 558.3, 28.9, [3], 'Ferdinand Reich', 1863, 'Soft malleable metal that emits a "cry" when bent; crucial for touchscreens.', 'Zinc sphalerite ores.', 'Solvent extraction from zinc residues.', ['Indium Tin Oxide (ITO) touchscreen transparent conductors', 'Cryogenic vacuum seals and solders', 'InGaAs photodetectors and lasers'], [{f:'In2O3',n:'Indium Oxide',u:'ITO component'}], [{eq:'4In + 3O2 -> 2In2O3',t:'Oxidation',d:'Forms indium oxide.'}], 'Inhalation of ITO dust causes indium lung disease.'],
  [50, 'Sn', 'Tin', 118.71, 'post-transition-metal', 14, 5, 'p', 'Solid', '[Kr] 4d¹⁰ 5s² 5p²', [2,8,18,18,4], 1.96, 505.08, 2875, 7.31, 140, 708.6, 107.3, [2,4], 'Known since antiquity', 'Ancient', 'Soft malleable silvery metal that initiated the historic Bronze Age.', 'Cassiterite ore (SnO2).', 'Smelting cassiterite in furnaces.', ['Lead-free solder in electronics (SAC)', 'Tinplate corrosion coating for food cans', 'Float glass manufacturing bath'], [{f:'SnO2',n:'Tin Dioxide',u:'Gas sensors and ceramic glazes'}], [{eq:'Sn + 2HCl -> SnCl2 + H2',t:'Displacement',d:'Yields tin(II) chloride.'}], 'Non-toxic metal; organotins are toxic biocides.'],
  [51, 'Sb', 'Antimony', 121.76, 'metalloid', 15, 5, 'p', 'Solid', '[Kr] 4d¹⁰ 5s² 5p³', [2,8,18,18,5], 2.05, 903.78, 1860, 6.697, 140, 834.0, 103.2, [-3,3,5], 'Known since antiquity', 'Ancient', 'Lustrous gray metalloid that expands upon freezing, flame retardant synergist.', 'Stibnite needles (Sb2S3).', 'Roasting and carbon reduction.', ['Flame retardant synergist (Sb2O3) in textiles', 'Lead-acid storage battery grid hardener', 'Phase change computer memory chips'], [{f:'Sb2O3',n:'Antimony Trioxide',u:'Flame retardant'}], [{eq:'2Sb + 3Cl2 -> 2SbCl3',t:'Chlorination',d:'Direct reaction.'}], 'Toxic metalloid; chronic exposure harms heart and liver.'],
  [52, 'Te', 'Tellurium', 127.60, 'metalloid', 16, 5, 'p', 'Solid', '[Kr] 4d¹⁰ 5s² 5p⁴', [2,8,18,18,6], 2.10, 722.66, 1261, 6.24, 142, 869.3, 190.2, [-2,2,4,6], 'Franz-Joseph Müller von Reichenstein', 1782, 'Brittle silvery metalloid used in thin-film solar and thermoelectric cooling.', 'Copper refining slimes.', 'Oxidative roasting of anode slimes.', ['Cadmium telluride (CdTe) utility solar modules', 'Bismuth telluride thermoelectric coolers', 'Phase-change rewritable optical media'], [{f:'Bi2Te3',n:'Bismuth Telluride',u:'Solid-state thermoelectric cooler'}], [{eq:'Te + 2H2O -> dimethyl telluride',t:'Metabolic',d:'Imparts garlic breath.'}], 'Toxic; tiny exposures cause pungent garlic body odor.'],
  [53, 'I', 'Iodine', 126.90, 'reactive-nonmetal', 17, 5, 'p', 'Solid', '[Kr] 4d¹⁰ 5s² 5p⁵', [2,8,18,18,7], 2.66, 386.85, 457.4, 4.933, 133, 1008.4, 295.2, [-1,1,3,5,7], 'Bernard Courtois', 1811, 'Dark lustrous halogen crystals sublimating into beautiful violet fumes.', 'Caliche nitrate beds and gas brines.', 'Chlorine oxidation of iodide brine.', ['Iodized salt to prevent thyroid goiter', 'Povidone-iodine medical antiseptic', 'X-ray CT contrast agents and I-131 thyroid cancer cure'], [{f:'KI',n:'Potassium Iodide',u:'Nutritional thyroid supplement'},{f:'I2',n:'Elemental Iodine',u:'Antiseptic'}], [{eq:'I2 + starch -> deep blue complex',t:'Indicator',d:'Classic diagnostic starch test.'}], 'Corrosive crystal; vapor causes eye and respiratory irritation.'],
  [54, 'Xe', 'Xenon', 131.29, 'noble-gas', 18, 5, 'p', 'Gas', '[Kr] 4d¹⁰ 5s² 5p⁶', [2,8,18,18,8], 2.60, 161.40, 165.03, 5.894, 108, 1170.4, -77, [2,4,6,8], 'William Ramsay & Morris Travers', 1898, 'Heavy noble gas that disproved inertness by forming stable chemical fluorides.', 'Atmospheric trace gas.', 'Cryogenic liquid air distillation.', ['Ion propulsion thrusters for deep space probes', 'High-intensity automotive headlamps and IMAX projectors', 'Neuroprotective general anesthesia'], [{f:'XeF4',n:'Xenon Tetrafluoride',u:'Milestone noble gas fluoride'}], [{eq:'Xe + 2F2 -> XeF4',t:'Bartlett Synthesis',d:'Forms crystalline fluoride.'}], 'Non-toxic inert gas; acts as an asphyxiant and anesthetic.'],

  // 55-71 (Period 6 Alkali, Alkaline Earth & Lanthanides)
  [55, 'Cs', 'Cesium', 132.91, 'alkali-metal', 1, 6, 's', 'Solid', '[Xe] 6s¹', [2,8,18,18,8,1], 0.79, 301.59, 944, 1.93, 260, 375.7, 46.9, [1], 'Robert Bunsen & Gustav Kirchhoff', 1860, 'Most reactive and electropositive stable metal, defines the standard SI second.', 'Pollucite pegmatite mineral.', 'Reduction of cesium chloride with calcium.', ['Cesium beam atomic clocks (defines the SI second: 9,192,631,770 Hz)', 'Cesium formate heavy drilling fluids for deep oil exploration', 'Photoelectric cells'], [{f:'CsCl',n:'Cesium Chloride',u:'Centrifugation density gradient'}], [{eq:'2Cs + 2H2O -> 2CsOH + H2',t:'Explosive Reaction',d:'Shatters glass violently.'}], 'Pyrophoric; ignites instantly in air and explodes with water.'],
  [56, 'Ba', 'Barium', 137.33, 'alkaline-earth', 2, 6, 's', 'Solid', '[Xe] 6s²', [2,8,18,18,8,2], 0.89, 1000, 2170, 3.62, 215, 502.9, 13.95, [2], 'Carl Wilhelm Scheele & Humphry Davy', 1808, 'Heavy alkaline-earth metal creating brilliant emerald-green pyrotechnics.', 'Barite mineral (BaSO4).', 'Aluminothermic reduction of BaO.', ['Gastrointestinal diagnostic X-ray barium meal (BaSO4)', 'Barite heavy drilling mud for petroleum wells', 'Emerald green fireworks and pyrotechnic flares'], [{f:'BaSO4',n:'Barium Sulfate',u:'Radiopaque X-ray contrast agent'}], [{eq:'Ba + 2H2O -> Ba(OH)2 + H2',t:'Displacement',d:'Vigorous reaction in water.'}], 'Soluble barium salts are highly toxic muscle poisons; BaSO4 is insoluble and safe.'],
  [57, 'La', 'Lanthanum', 138.91, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 5d¹ 6s²', [2,8,18,18,9,2], 1.10, 1193, 3737, 6.162, 195, 538.1, 48, [3], 'Carl Gustaf Mosander', 1839, 'First lanthanide element, gives its name to the entire 15-element series.', 'Bastnäsite and monazite ores.', 'Molten fluoride electrolysis.', ['Hybrid car NiMH rechargeable batteries', 'High-refractive optical glass for camera lenses', 'Fluid catalytic cracking catalysts in petroleum refineries'], [{f:'La2O3',n:'Lanthanum Oxide',u:'High-index low-dispersion optical glass'}], [{eq:'4La + 3O2 -> 2La2O3',t:'Oxidation',d:'Forms basic lanthanum oxide.'}], 'Low to moderate toxicity.'],
  [58, 'Ce', 'Cerium', 140.12, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f¹ 5d¹ 6s²', [2,8,18,19,9,2], 1.12, 1068, 3716, 6.77, 185, 534.4, 50, [3,4], 'Martin Heinrich Klaproth & Jöns Jacob Berzelius', 1803, 'Most abundant rare earth metal, versatile redox catalyst in both +3 and +4 states.', 'Bastnäsite deposits.', 'Electrowinning from molten chloride salt.', ['Precision optical glass polishing slurry (ceria powder CeO2)', 'Automotive catalytic converters (oxygen storage promoter)', 'Self-cleaning oven catalytic interior walls', 'Mischmetal flint in lighter spark wheels'], [{f:'CeO2',n:'Cerium(IV) Oxide (Ceria)',u:'Glass polishing compound and diesel soot catalyst'}], [{eq:'2CeO2 <-> Ce2O3 + 0.5O2',t:'Redox Cycling',d:'Oxygen storage buffer in car converters.'}], 'Low toxicity metal.'],
  [59, 'Pr', 'Praseodymium', 140.91, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f³ 6s²', [2,8,18,21,8,2], 1.13, 1208, 3793, 6.77, 185, 527.0, 50, [3,4], 'Carl Auer von Welsbach', 1885, 'Soft silvery rare earth creating vibrant yellow-green glass and powerful magnets.', 'Monazite and bastnäsite.', 'Molten salt electrolysis.', ['Didymium glass for welder safety goggles', 'Neodymium-praseodymium supermagnets in EV drive motors', 'Zircon yellow ceramic glazes'], [{f:'Pr2O3',n:'Praseodymium Oxide',u:'Ceramic and glass pigment'}], [{eq:'4Pr + 3O2 -> 2Pr2O3',t:'Oxidation',d:'Forms pale green oxide.'}], 'Low to moderate toxicity.'],
  [60, 'Nd', 'Neodymium', 144.24, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f⁴ 6s²', [2,8,18,22,8,2], 1.14, 1297, 3347, 7.01, 185, 533.1, 50, [3], 'Carl Auer von Welsbach', 1885, 'Forms the strongest permanent magnets on Earth (Nd2Fe14B) driving electric motors.', 'Bastnäsite and monazite.', 'Reduction of anhydrous fluoride with calcium.', ['NdFeB supermagnets for EV motors, wind turbines, and audio speakers', 'Nd:YAG infrared medical and industrial lasers', 'Neodymium purple-tinted decorative art glass'], [{f:'Nd2Fe14B',n:'Neodymium Magnet',u:'World strongest commercial permanent magnet'}], [{eq:'4Nd + 3O2 -> 2Nd2O3',t:'Oxidation',d:'Forms blue-purple oxide.'}], 'Magnetic pinching hazard in neodymium permanent magnets.'],
  [61, 'Pm', 'Promethium', 145.0, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f⁵ 6s²', [2,8,18,23,8,2], 1.13, 1315, 3273, 7.26, 185, 540.0, 50, [3], 'Chien Shiung Wu, Jacob Marinsky & Lawrence Glendenin', 1945, 'Only radioactive lanthanide, named after Prometheus who brought fire to humanity.', 'Uranium nuclear fission byproduct.', 'Ion exchange separation from reactor wastes.', ['Nuclear betavoltaic micro-batteries for space probes', 'Luminous paint for dials and guided missile instruments', 'Thickness measurement gauges'], [{f:'Pm2O3',n:'Promethium Oxide',u:'Luminescent phosphors'}], [{eq:'147Pm -> 147Sm + beta',t:'Decay',d:'Pure soft beta emitter.'}], 'Radioactive beta emitter; handles with radiation protocols.'],
  [62, 'Sm', 'Samarium', 150.36, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f⁶ 6s²', [2,8,18,24,8,2], 1.17, 1345, 2067, 7.52, 185, 544.5, 50, [2,3], 'Paul-Émile Lecoq de Boisbaudran', 1879, 'Lanthanide forming high-temperature permanent magnets (SmCo) resistant to demagnetization.', 'Monazite sands.', 'Distillation reduction with lanthanum.', ['Samarium-Cobalt (SmCo) high-temperature aircraft magnets', 'Samarium-153 Quadramet targeted cancer bone pain relief', 'Neutron absorber in nuclear reactor control rods'], [{f:'SmCo5',n:'Samarium-Cobalt',u:'Heat-resistant permanent magnet'}], [{eq:'4Sm + 3O2 -> 2Sm2O3',t:'Oxidation',d:'Forms yellow oxide.'}], 'Low to moderate toxicity.'],
  [63, 'Eu', 'Europium', 151.96, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f⁷ 6s²', [2,8,18,25,8,2], 1.20, 1099, 1802, 5.244, 185, 547.1, 50, [2,3], 'Eugène-Anatole Demarçay', 1901, 'Most chemically reactive lanthanide, provides the red phosphor in TV displays and anti-counterfeiting ink.', 'Bastnäsite and monazite.', 'Reduction of Eu2O3 with lanthanum in high vacuum.', ['Anti-counterfeiting phosphorescent ink in Euro banknotes', 'Red and blue phosphors in OLED displays and fluorescent lamps', 'Control rods in nuclear reactors'], [{f:'Eu2O3',n:'Europium(III) Oxide',u:'Brilliant red phosphor activator'}], [{eq:'2Eu + 2H2O -> 2Eu(OH)2 + H2',t:'Displacement',d:'Reacts vigorously with water.'}], 'Water-reactive; oxidizes rapidly in humid air.'],
  [64, 'Gd', 'Gadolinium', 157.25, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f⁷ 5d¹ 6s²', [2,8,18,25,9,2], 1.20, 1585, 3546, 7.90, 180, 593.4, 50, [3], 'Jean Charles Galissard de Marignac', 1880, 'Possesses the highest thermal neutron capture cross-section and 7 unpaired electrons.', 'Monazite sands.', 'Calcium reduction of anhydrous GdF3.', ['Gadolinium MRI contrast agents for vascular medical imaging', 'Neutron shielding shut-down systems in nuclear reactors', 'Magnetic refrigeration via giant magnetocaloric effect'], [{f:'Gd-DTPA',n:'Gadopentetate Dimeglumine',u:'Standard clinical MRI contrast agent'}], [{eq:'4Gd + 3O2 -> 2Gd2O3',t:'Oxidation',d:'Forms white oxide.'}], 'Free Gd3+ is toxic; clinical MRI agents use tight chelation complexes.'],
  [65, 'Tb', 'Terbium', 158.93, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f⁹ 6s²', [2,8,18,27,8,2], 1.20, 1629, 3503, 8.23, 175, 565.8, 50, [3,4], 'Carl Gustaf Mosander', 1843, 'Emits a sharp, vivid lemon-green luminescence and forms giant magnetostrictive alloys.', 'Xenotime and ion-adsorption clays.', 'Reduction of TbF3 with calcium.', ['Terfenol-D giant magnetostrictive sonar transducers and acoustic actuators', 'Green phosphors in high-definition displays and fluorescent lighting', 'Solid-state naval defense lasers'], [{f:'Tb4O7',n:'Terbium(III,IV) Oxide',u:'Green phosphor precursor'}], [{eq:'Tb4O7 + reducing -> Tb2O3',t:'Reduction',d:'Color change from brown to white.'}], 'Low toxicity metal.'],
  [66, 'Dy', 'Dysprosium', 162.50, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f¹⁰ 6s²', [2,8,18,28,8,2], 1.22, 1680, 2840, 8.54, 175, 573.0, 50, [3], 'Paul-Émile Lecoq de Boisbaudran', 1886, 'Has the highest magnetic susceptibility among elements; prevents EV magnets from failing at high heat.', 'Monazite and ion-adsorption clays.', 'Calcium reduction of DyF3.', ['High-temperature thermal stabilizer for NdFeB EV motor magnets', 'Nuclear reactor control rods (dysprosium titanate)', 'Terfenol-D magnetostrictive smart materials'], [{f:'Dy2O3',n:'Dysprosium Oxide',u:'Thermal magnet additive and optical glaze'}], [{eq:'4Dy + 3O2 -> 2Dy2O3',t:'Oxidation',d:'Slow oxidation.'}], 'Low toxicity metal.'],
  [67, 'Ho', 'Holmium', 164.93, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f¹¹ 6s²', [2,8,18,29,8,2], 1.23, 1734, 2993, 8.79, 175, 581.0, 50, [3], 'Per Teodor Cleve', 1879, 'Possesses the highest magnetic moment of any element; acts as a magnetic flux concentrator.', 'Monazite and xenotime.', 'Reduction of HoF3 with calcium metal.', ['Magnetic pole pieces concentrating high-field MRI magnets', 'Holmium:YAG lasers for endoscopic kidney stone lithotripsy', 'Spectrophotometer wavelength calibration filters'], [{f:'Ho2O3',n:'Holmia',u:'Wavelength calibration standard and laser dopant'}], [{eq:'4Ho + 3O2 -> 2Ho2O3',t:'Oxidation',d:'Yellow oxide.'}], 'Low toxicity metal.'],
  [68, 'Er', 'Erbium', 167.26, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f¹² 6s²', [2,8,18,30,8,2], 1.24, 1802, 3141, 9.066, 175, 589.3, 50, [3], 'Carl Gustaf Mosander', 1843, 'Crucial for global internet telecommunications via Erbium-Doped Fiber Amplifiers (EDFA).', 'Xenotime and clay deposits.', 'Reduction of ErF3 with calcium.', ['Erbium-Doped Fiber Amplifiers (EDFA) powering trans-oceanic internet cables', 'Er:YAG dental and cosmetic laser skin resurfacing', 'Pink decorative coloring in cubic zirconia and glassware'], [{f:'Er2O3',n:'Erbium Oxide',u:'Telecommunications fiber optical amplifier dopant'}], [{eq:'4Er + 3O2 -> 2Er2O3',t:'Oxidation',d:'Forms pink oxide.'}], 'Low toxicity metal.'],
  [69, 'Tm', 'Thulium', 168.93, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f¹³ 6s²', [2,8,18,31,8,2], 1.25, 1818, 2223, 9.32, 175, 596.7, 50, [3], 'Per Teodor Cleve', 1879, 'Second least abundant lanthanide, yields portable X-ray sources when irradiated.', 'Monazite ores.', 'Lanthanum reduction of Tm2O3 in vacuum.', ['Portable medical X-ray sources (Thulium-170)', 'Thulium fiber lasers for high-precision surgical resection', 'Euro banknote anti-counterfeiting blue fluorescence'], [{f:'Tm2O3',n:'Thulium Oxide',u:'Laser crystal host'}], [{eq:'4Tm + 3O2 -> 2Tm2O3',t:'Oxidation',d:'Forms pale green oxide.'}], 'Low toxicity metal.'],
  [70, 'Yb', 'Ytterbium', 173.05, 'lanthanide', 3, 6, 'f', 'Solid', '[Xe] 4f¹⁴ 6s²', [2,8,18,32,8,2], 1.10, 1097, 1469, 6.90, 175, 603.4, 50, [2,3], 'Jean Charles Galissard de Marignac', 1878, 'Soft malleable metal with high precision optical atomic clocks and fiber lasers.', 'Monazite and xenotime.', 'Distillation from Yb2O3 and lanthanum.', ['High-power industrial cutting ytterbium fiber lasers', 'Next-generation optical atomic clocks', 'Stainless steel grain refinement'], [{f:'Yb2O3',n:'Ytterbium Oxide',u:'Industrial cutting fiber laser amplifier'}], [{eq:'4Yb + 3O2 -> 2Yb2O3',t:'Oxidation',d:'Forms white oxide.'}], 'Low toxicity metal.'],
  [71, 'Lu', 'Lutetium', 174.97, 'lanthanide', 3, 6, 'd', 'Solid', '[Xe] 4f¹⁴ 5d¹ 6s²', [2,8,18,32,9,2], 1.27, 1925, 3675, 9.841, 160, 523.5, 50, [3], 'Georges Urbain & Carl Auer von Welsbach', 1907, 'Heaviest, hardest, and densest lanthanide, used in targeted cancer radiopharmaceuticals.', 'Trace byproduct in xenotime.', 'Reduction of LuF3 with calcium metal.', ['Lutetium-177 targeted neuroendocrine and prostate cancer radioligand therapy', 'PET medical scanner LSO scintillation crystals', 'Petroleum hydrocarbon cracking catalysts'], [{f:'177Lu-PSMA',n:'Lutetium-177 PSMA',u:'Breakthrough targeted prostate cancer drug'}], [{eq:'4Lu + 3O2 -> 2Lu2O3',t:'Oxidation',d:'White refractory oxide.'}], 'Low toxicity metal; Lu-177 handled as therapeutic radioisotope.'],

  // 72-86 (Period 6 Heavy Transition Metals to Radon)
  [72, 'Hf', 'Hafnium', 178.49, 'transition-metal', 4, 6, 'd', 'Solid', '[Xe] 4f¹⁴ 5d² 6s²', [2,8,18,32,10,2], 1.30, 2506, 4876, 13.31, 159, 658.5, 0, [4], 'Dirk Coster & George de Hevesy', 1923, 'Extraordinary neutron absorber and high-k gate dielectric in Intel computer processors.', 'Zircon mineral ores (1-4% Hf).', 'Separation from zirconium via solvent extraction.', ['Intel microchip high-k metal gate dielectric (HfO2)', 'Nuclear submarine reactor control rods', 'Plasma cutting torch electrode tips'], [{f:'HfO2',n:'Hafnium Dioxide',u:'Nanoscale transistor gate insulator'}], [{eq:'Hf + O2 -> HfO2',t:'Oxidation',d:'Passivating dielectric film.'}], 'Fine hafnium powder is pyrophoric.'],
  [73, 'Ta', 'Tantalum', 180.95, 'transition-metal', 5, 6, 'd', 'Solid', '[Xe] 4f¹⁴ 5d³ 6s²', [2,8,18,32,11,2], 1.50, 3290, 5731, 16.69, 146, 761.0, 31.0, [5], 'Anders Gustaf Ekeberg', 1802, 'Immune to all chemical attack below 150°C, essential for smartphone capacitors.', 'Coltan mineral ores (columbite-tantalite).', 'Sodium reduction of potassium fluorotantalate.', ['Miniature tantalum electrolytic capacitors in smartphones and laptops', 'Surgical biocompatible bone pins, skull plates, and cranial mesh', 'Corrosive chemical heat exchangers and acid reactors'], [{f:'Ta2O5',n:'Tantalum Pentoxide',u:'High dielectric constant capacitor film'}], [{eq:'4Ta + 5O2 -> 2Ta2O5',t:'Synthesis',d:'High-temperature oxidation.'}], 'Completely inert, biocompatible, non-toxic metal.'],
  [74, 'W', 'Tungsten', 183.84, 'transition-metal', 6, 6, 'd', 'Solid', '[Xe] 4f¹⁴ 5d⁴ 6s²', [2,8,18,32,12,2], 2.36, 3695, 5828, 19.25, 139, 770.0, 78.6, [2,4,6], 'Carl Wilhelm Scheele', 1781, 'Highest melting point of all metallic elements (3422°C / 3695 K) and ultra-high tensile strength.', 'Wolframite and scheelite ores.', 'Hydrogen reduction of purified WO3 powder.', ['Tungsten carbide (WC) ultra-hard industrial machining tools and drill bits', 'Filaments in traditional incandescent bulbs and electron guns', 'Kinetic energy armor-piercing anti-tank penetrators', 'Fusion reactor divertor plasma-facing tiles (ITER)'], [{f:'WC',n:'Tungsten Carbide',u:'Industrial drilling and metal machining tools'}], [{eq:'WO3 + 3H2 -> W + 3H2O',t:'Hydrogen Reduction',d:'Metallurgical extraction of pure tungsten powder.'}], 'Non-toxic elemental metal; tungsten carbide dust causes hard metal lung disease.'],
  [75, 'Re', 'Rhenium', 186.21, 'transition-metal', 7, 6, 'd', 'Solid', '[Xe] 4f¹⁴ 5d⁵ 6s²', [2,8,18,32,13,2], 1.90, 3459, 5869, 21.02, 137, 760.0, 14.0, [4,6,7], 'Walter Noddack, Ida Tacke & Otto Berg', 1925, 'One of the rarest elements in Earth crust, third highest melting point of all metals.', 'Porphyry copper-molybdenum roaster flue gases.', 'Hydrogen reduction of ammonium perrhenate.', ['Jet turbine single-crystal nickel superalloy blades (up to 6% Re)', 'Platinum-rhenium reformate catalysts for lead-free high-octane gasoline', 'Mass spectrometer filament wires'], [{f:'Re2O7',n:'Rhenium Heptoxide',u:'Precursor for organometallic catalysts'}], [{eq:'4Re + 7O2 -> 2Re2O7',t:'Synthesis',d:'Forms volatile yellow oxide.'}], 'Low toxicity metal.'],
  [76, 'Os', 'Osmium', 190.23, 'transition-metal', 8, 6, 'd', 'Solid', '[Xe] 4f¹⁴ 5d⁶ 6s²', [2,8,18,32,14,2], 2.20, 3306, 5285, 22.59, 135, 840.0, 106.1, [2,3,4,8], 'Smithson Tennant', 1803, 'Densest naturally occurring element (22.59 g/cm³, twice as dense as lead).', 'Platinum group refining residue.', 'Hydrogen reduction of osmium tetroxide.', ['Wear-resistant fountain pen tipping alloys and phonograph needles', 'Osmium tetroxide lipid histological staining for electron microscopy', 'High-wear electrical contacts'], [{f:'OsO4',n:'Osmium Tetroxide',u:'Biological electron microscopy lipid fixative'}], [{eq:'Os + 2O2 -> OsO4',t:'Oxidation',d:'Sublimates into pungent toxic tetroxide gas.'}], 'OsO4 vapor is extremely dangerous, attacking cornea to cause blindness.'],
  [77, 'Ir', 'Iridium', 192.22, 'transition-metal', 9, 6, 'd', 'Solid', '[Xe] 4f¹⁴ 5d⁷ 6s²', [2,8,18,32,15,2], 2.20, 2719, 4701, 22.56, 136, 880.0, 151.0, [3,4], 'Smithson Tennant', 1803, 'Most corrosion-resistant metal known; famous Cretaceous asteroid impact layer biomarker.', 'Nickel-copper matte refining.', 'Refining from insoluble platinum residues.', ['Proton Exchange Membrane (PEM) green hydrogen electrolyzers', 'Crucibles for growing high-purity laser and telecom single crystals', 'High-performance spark plug electrode tips', 'Iridium-192 industrial radiography weld testing'], [{f:'IrO2',n:'Iridium Dioxide',u:'Premier PEM water electrolysis anode catalyst'}], [{eq:'2H2O --(IrO2 catalyst)--> O2 + 4H+ + 4e-',t:'Oxygen Evolution',d:'Green hydrogen generation.'}], 'Non-toxic elemental noble metal.'],
  [78, 'Pt', 'Platinum', 195.08, 'transition-metal', 10, 6, 'd', 'Solid', '[Xe] 4f¹⁴ 5d⁹ 6s¹', [2,8,18,32,17,1], 2.28, 2041.4, 4098, 21.45, 139, 870.0, 205.3, [2,4], 'Antonio de Ulloa', 1735, 'Precious noble metal, extraordinary catalyst for clean automotive and cancer chemotherapy.', 'Bushveld complex and Sudbury ores.', 'Aqua regia dissolution and thermal refining.', ['Automotive catalytic converters for diesel vehicles', 'Cisplatin anticancer chemotherapy drugs', 'Hydrogen fuel cell PEM electrode electrocatalysts', 'Luxury investment jewelry and laboratory crucibles'], [{f:'PtCl2(NH3)2',n:'Cisplatin',u:'Standard life-saving cancer chemotherapy drug'}], [{eq:'2H2 + O2 --(Pt)--> 2H2O',t:'Fuel Cell Catalysis',d:'Clean electricity generation.'}], 'Inert biocompatible metal; soluble platinum chloroplatinates can cause allergic asthma.'],
  [79, 'Au', 'Gold', 196.97, 'transition-metal', 11, 6, 'd', 'Solid', '[Xe] 4f¹⁴ 5d¹⁰ 6s¹', [2,8,18,32,18,1], 2.54, 1337.33, 3129, 19.30, 144, 890.1, 222.8, [1,3], 'Known since antiquity', 'Ancient', 'Most malleable and ductile metal, treasured throughout history as monetary wealth.', 'Native gold quartz veins and placer gravels.', 'Cyanide leaching followed by carbon adsorption and electrowinning.', ['Monetary reserve bullion, sovereign coins, and fine jewelry', 'Corrosion-proof wire bonding and contacts in microchips and smartphones', 'Reflective infrared gold heat shields on spacecraft and astronaut visors', 'Colloidal gold rapid medical diagnostic test kits (e.g. COVID/pregnancy)'], [{f:'HAuCl4',n:'Chloroauric Acid',u:'Synthesis of gold nanoparticles'}], [{eq:'Au + HNO3 + 4HCl -> HAuCl4 + NO + 2H2O',t:'Aqua Regia Dissolution',d:'Dissolves noble gold into chloroauric acid.'}], 'Non-toxic, highly biocompatible, hypoallergenic.'],
  [80, 'Hg', 'Mercury', 200.59, 'transition-metal', 12, 6, 'd', 'Liquid', '[Xe] 4f¹⁴ 5d¹⁰ 6s²', [2,8,18,32,18,2], 2.00, 234.32, 629.88, 13.534, 151, 1007.1, -48, [1,2], 'Known since antiquity', 'Ancient', 'Only metallic element liquid at standard temperature and pressure (historically quicksilver).', 'Cinnabar mineral ore (HgS).', 'Roasting cinnabar in air and condensing mercury vapor.', ['Fluorescent lighting vapor tubes', 'Artisanal gold amalgamation extraction', 'Dental amalgam fillings historically', 'Tilt switches and mercury barometers'], [{f:'HgS',n:'Cinnabar / Vermilion',u:'Ancient red mineral pigment'},{f:'(CH3)2Hg',n:'Dimethylmercury',u:'Super-potent neurotoxin'}], [{eq:'HgS + O2 -> Hg + SO2',t:'Roasting',d:'Smelting cinnabar ore.'}], 'Extremely toxic volatile neurotoxin; bioaccumulates up the aquatic food chain (Minamata disease).'],
  [81, 'Tl', 'Thallium', 204.38, 'post-transition-metal', 13, 6, 'p', 'Solid', '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹', [2,8,18,32,18,3], 1.62, 577, 1746, 11.85, 170, 589.4, 19.2, [1,3], 'William Crookes', 1861, 'Soft malleable heavy metal whose salts are tasteless, odorless, and notoriously deadly.', 'Byproduct of zinc and lead smelting.', 'Precipitation from lead smelter flue dust.', ['Cardiac stress test medical scans (Thallium-201)', 'Infrared optical lenses (KRS-5)', 'High-temperature cuprate superconductors'], [{f:'Tl2SO4',n:'Thallium Sulfate',u:'Historical rodenticide; now banned globally'}], [{eq:'4Tl + O2 -> 2Tl2O',t:'Oxidation',d:'Tarnishes rapidly in air.'}], 'Extremely toxic; mimics potassium in cells, causing alopecia (hair loss) and nervous collapse.'],
  [82, 'Pb', 'Lead', 207.2, 'post-transition-metal', 14, 6, 'p', 'Solid', '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²', [2,8,18,32,18,4], 2.33, 600.61, 2022, 11.34, 175, 715.6, 35.1, [2,4], 'Known since antiquity', 'Ancient', 'Dense malleable soft metal used for millennia, final stable decay product of uranium.', 'Galena lead sulfide ore (PbS).', 'Smelting galena in blast furnaces.', ['12-volt lead-acid vehicle SLI starting batteries (85% of all lead use)', 'Radiation shielding aprons and walls for medical X-ray/CT scanners', 'Acoustic soundproofing dampers', 'Lead crystal glass historically'], [{f:'PbO2',n:'Lead Dioxide',u:'Positive plate in car lead-acid batteries'},{f:'PbS',n:'Galena',u:'Lead ore and ancient kohl eyeliner'}], [{eq:'Pb + PbO2 + 2H2SO4 <-> 2PbSO4 + 2H2O',t:'Lead-Acid Battery Cycle',d:'Electrochemical discharge/charge cycle in cars.'}], 'Cumulative neurotoxin causing cognitive impairment and anemia, especially dangerous to developing children.'],
  [83, 'Bi', 'Bismuth', 208.98, 'post-transition-metal', 15, 6, 'p', 'Solid', '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³', [2,8,18,32,18,5], 2.02, 544.7, 1837, 9.78, 155, 703.0, 91.2, [3,5], 'Known since antiquity', 'Ancient', 'Forms mesmerizing rainbow stair-step hopper crystals, least toxic heavy metal.', 'Bismuthinite (Bi2S3) and copper/lead byproduct.', 'Reduction of Bi2O3 with carbon.', ['Pepto-Bismol stomach soothing medicine (bismuth subsalicylate)', 'Non-toxic replacement for lead in hunting shot and plumbing fixtures', 'Low-melting fusible safety alloys (Wood metal) for fire sprinklers', 'Bismuth telluride thermoelectric coolers'], [{f:'C7H5BiO4',n:'Bismuth Subsalicylate',u:'Active ingredient in antidiarrheal medicines'}], [{eq:'4Bi + 3O2 -> 2Bi2O3',t:'Oxidation',d:'Yellow oxide.'}], 'Virtually non-toxic heavy metal, unique among neighboring elements.'],
  [84, 'Po', 'Polonium', 209.0, 'post-transition-metal', 16, 6, 'p', 'Solid', '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴', [2,8,18,32,18,6], 2.00, 527, 1235, 9.196, 168, 812.1, 183.3, [2,4], 'Marie & Pierre Curie', 1898, 'Intensely radioactive alpha emitter named by Marie Curie after her homeland Poland.', 'Uranium decay chain and neutron irradiation of bismuth-209 in reactors.', 'Reactor synthesis from bismuth.', ['Antistatic brushes for photographic film and cleanrooms', 'Radioisotope thermoelectric heat sources for space probes'], [{f:'210Po',n:'Polonium-210',u:'High specific alpha activity emitter'}], [{eq:'210Po -> 206Pb + alpha',t:'Alpha Decay',d:'Releases 140 W/g of thermal energy.'}], 'Extremely radiotoxic; ingestion of microgram quantities is fatal via radiation sickness.'],
  [85, 'At', 'Astatine', 210.0, 'reactive-nonmetal', 17, 6, 'p', 'Solid', '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵', [2,8,18,32,18,7], 2.20, 575, 610, 6.35, 140, 899.0, 270.1, [-1,1,3,5], 'Dale Corson, Kenneth MacKenzie & Emilio Segrè', 1940, 'Rarest naturally occurring element in Earth crust (less than 30 grams in entire planet).', 'Natural decay of uranium/thorium; synthesized by alpha bombardment of bismuth-209.', 'Cyclotron synthesis: 209Bi(alpha,2n)211At.', ['Targeted Alpha Therapy (TAT) for metastatic cancer cells using Astatine-211'], [{f:'211At-MABG',n:'Astatine-211 MABG',u:'Targeted radiopharmaceutical for neuroblastoma'}], [{eq:'211At -> 207Bi + alpha',t:'Alpha Decay',d:'Short-range cancer cell destruction.'}], 'Intensely radioactive; handles only in specialized hot cells.'],
  [86, 'Rn', 'Radon', 222.0, 'noble-gas', 18, 6, 'p', 'Gas', '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶', [2,8,18,32,18,8], 2.20, 202, 211.3, 9.73, 150, 1037.0, -68, [2], 'Friedrich Ernst Dorn', 1900, 'Colorless, odorless, radioactive noble gas accumulating in basements from rock uranium decay.', 'Continuous decay of radium-226 in granite rock and soil.', 'Collected from radium salt decay.', ['Historical radiation seeds for cancer brachytherapy', 'Hydrological tracer for groundwater monitoring'], [{f:'RnF2',n:'Radon Difluoride',u:'Radioactive fluoride'}], [{eq:'222Rn -> 218Po + alpha',t:'Alpha Decay',d:'Inhaled decay daughters damage lung tissue.'}], 'Major public health hazard; leading cause of lung cancer in non-smokers.'],

  // 87-88 (Period 7 Alkali & Alkaline Earth)
  [87, 'Fr', 'Francium', 223.0, 'alkali-metal', 1, 7, 's', 'Solid', '[Rn] 7s¹', [2,8,18,32,18,8,1], 0.70, 300, 950, 1.87, 260, 380.0, 47.0, [1], 'Marguerite Perey', 1939, 'Second rarest natural element, intensely radioactive with a half-life of just 22 minutes.', 'Uranium actinium decay series; synthesized by gold heavy-ion bombardment.', 'Linear accelerator synthesis.', ['Atomic physics precision tests of the Standard Model and parity violation in magneto-optical traps'], [{f:'FrCl',n:'Francium Chloride',u:'Theoretical radiochemical solution'}], [{eq:'223Fr -> 223Ra + beta',t:'Beta Decay',d:'Half-life of 22 minutes.'}], 'Extremely radioactive and thermally self-vaporizing in weighable amounts.'],
  [88, 'Ra', 'Radium', 226.0, 'alkaline-earth', 2, 7, 's', 'Solid', '[Rn] 7s²', [2,8,18,32,18,8,2], 0.90, 973, 2010, 5.5, 221, 509.3, 9.65, [2], 'Marie & Pierre Curie', 1898, 'Luminescent radioactive metal isolated from pitchblende by Marie Curie.', 'Uranium ores (pitchblende).', 'Fractional crystallization of barium-radium chloride.', ['Radium-223 dichloride (Xofigo) targeted prostate cancer bone metastasis cure', 'Luminous watch dials historically (Radium Girls era)'], [{f:'223RaCl2',n:'Radium-223 Dichloride',u:'First approved alpha emitter cancer therapeutic'}], [{eq:'226Ra -> 222Rn + alpha',t:'Alpha Decay',d:'Forms radon gas with half-life of 1600 years.'}], 'Intensely radiotoxic; bone-seeking alpha emitter causing osteosarcoma.'],

  // 89-103 (Actinides)
  [89, 'Ac', 'Actinium', 227.0, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 6d¹ 7s²', [2,8,18,32,18,9,2], 1.10, 1323, 3471, 10.07, 195, 499.0, 35, [3], 'André-Louis Debierne', 1899, 'First actinide, glows with an eerie pale blue light in the dark due to intense radioactivity.', 'Uranium ores and neutron bombardment of radium-226.', 'Extraction from irradiated radium targets.', ['Actinium-225 Targeted Alpha Therapy (TAT) cancer eradication clinical trials', 'Neutron sources when combined with beryllium'], [{f:'225Ac-PSMA',n:'Actinium-225 PSMA',u:'Groundbreaking alpha cancer therapy'}], [{eq:'227Ac -> 227Th + beta',t:'Beta Decay',d:'Emits blue radioluminescence.'}], 'Extremely radiotoxic.'],
  [90, 'Th', 'Thorium', 232.04, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 6d² 7s²', [2,8,18,32,18,10,2], 1.30, 2115, 5061, 11.72, 180, 587.0, 112.0, [4], 'Jöns Jacob Berzelius', 1828, 'Naturally abundant weakly radioactive metal, key fuel for proliferation-resistant nuclear power.', 'Monazite phosphate beach sands.', 'Sulfuric acid digestion of monazite followed by solvent extraction.', ['Thorium molten salt nuclear breeder reactors (converts to fissile U-233)', 'High-temperature gas tungsten arc (TIG) welding electrodes', 'Gas mantle lighting historically (ThO2)'], [{f:'ThO2',n:'Thoria',u:'High-melting ceramic (3390°C)'}], [{eq:'232Th + n -> 233Th -> 233Pa -> 233U (fissile)',t:'Nuclear Breeding',d:'Fertile thorium fuel cycle.'}], 'Mildly radioactive alpha emitter; radiotoxic if inhaled in dust.'],
  [91, 'Pa', 'Protactinium', 231.04, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 5f² 6d¹ 7s²', [2,8,18,32,20,9,2], 1.50, 1841, 4300, 15.37, 180, 568.0, 50, [4,5], 'Otto Hahn & Lise Meitner', 1917, 'Dense radioactive metal forming a crucial intermediate in the thorium nuclear fuel cycle.', 'Uranium processing residues.', 'Extraction from spent fuel or irradiated thorium.', ['Dating marine sediments in oceanography (Pa-231/Th-230)', 'Fundamental actinide chemical physics'], [{f:'Pa2O5',n:'Protactinium Pentoxide',u:'White oxide'}], [{eq:'233Pa -> 233U + beta',t:'Beta Decay',d:'Thorium fuel cycle intermediate.'}], 'Highly radiotoxic alpha emitter.'],
  [92, 'U', 'Uranium', 238.03, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 5f³ 6d¹ 7s²', [2,8,18,32,21,9,2], 1.38, 1405.3, 4404, 18.95, 175, 597.6, 50, [3,4,5,6], 'Martin Heinrich Klaproth', 1789, 'Primary nuclear fuel powering commercial nuclear reactors and submarines via U-235 fission.', 'Uraninite / pitchblende ores.', 'In-situ leach mining followed by solvent extraction to yellowcake (U3O8).', ['Fuel for commercial clean nuclear energy reactors (U-235)', 'Depleted uranium armor plating and kinetic penetrators', 'Radioisotope production (Mo-99)'], [{f:'UO2',n:'Uranium Dioxide',u:'Standard nuclear power fuel pellet'},{f:'UF6',n:'Uranium Hexafluoride',u:'Gas centrifuge isotope enrichment'}], [{eq:'235U + n -> 141Ba + 92Kr + 3n + 200 MeV',t:'Nuclear Fission',d:'Core energy release in nuclear reactors.'}], 'Chemical heavy metal toxicity to kidneys combined with radioactivity risks.'],
  [93, 'Np', 'Neptunium', 237.0, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 5f⁴ 6d¹ 7s²', [2,8,18,32,22,9,2], 1.36, 917, 4273, 20.45, 175, 604.5, 50, [3,4,5,6], 'Edwin McMillan & Philip Abelson', 1940, 'First transuranic synthetic element discovered, named after the planet Neptune.', 'Byproduct in nuclear reactor spent fuel rods.', 'Chemical separation from irradiated reactor fuel.', ['Precursor target for producing Plutonium-238 space batteries (RTG)', 'High-energy neutron detection devices'], [{f:'NpO2',n:'Neptunium Dioxide',u:'Nuclear target material'}], [{eq:'237Np + n -> 238Np -> 238Pu + beta',t:'Neutron Capture',d:'Manufactures Pu-238 for NASA space probes.'}], 'Dangerous radioactive actinide.'],
  [94, 'Pu', 'Plutonium', 244.0, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 5f⁶ 7s²', [2,8,18,32,24,8,2], 1.28, 912.5, 3501, 19.84, 175, 584.7, 50, [3,4,5,6], 'Glenn T. Seaborg', 1940, 'Fissile transuranic metal powering deep-space NASA missions (Voyager, Perseverance) and nuclear weapons.', 'Produced in uranium reactors by neutron capture in U-238.', 'PUREX chemical reprocessing of irradiated reactor fuel.', ['Plutonium-238 Radioisotope Thermoelectric Generators (RTG) for NASA deep space probes', 'Mixed oxide (MOX) fuel for nuclear power reactors', 'Fissile material in nuclear defense arsenals'], [{f:'PuO2',n:'Plutonium Dioxide',u:'Heat source ceramic pellets in space probes'}], [{eq:'238U + n -> 239U -> 239Np -> 239Pu',t:'Breeding',d:'Reactor generation of fissile plutonium.'}], 'Extreme radiological toxin; alpha emitter that deposits in bone marrow and liver.'],
  [95, 'Am', 'Americium', 243.0, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 5f⁷ 7s²', [2,8,18,32,25,8,2], 1.30, 1449, 2880, 12.0, 175, 578.0, 50, [3,4], 'Glenn T. Seaborg', 1944, 'Radioactive element protecting millions of households worldwide in smoke detectors.', 'Decay of plutonium-241 in spent nuclear reactor fuel.', 'Chemical extraction from aged reactor plutonium.', ['Household ionization smoke detectors (Americium-241)', 'Industrial thickness measurement gauges', 'Neutron moisture probes in agriculture and civil engineering'], [{f:'241AmO2',n:'Americium-241 Oxide',u:'Microcurie alpha source in home smoke alarms'}], [{eq:'241Am -> 237Np + alpha (5.48 MeV)',t:'Alpha Ionization',d:'Ionizes air in smoke detector chamber.'}], 'Radioactive material; completely sealed and safe in household smoke alarms.'],
  [96, 'Cm', 'Curium', 247.0, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 5f⁷ 6d¹ 7s²', [2,8,18,32,25,9,2], 1.30, 1613, 3383, 13.51, 175, 581.0, 50, [3,4], 'Glenn T. Seaborg', 1944, 'Named after Marie and Pierre Curie, power source for Mars rover X-ray spectrometers.', 'Intense neutron irradiation of plutonium and americium in high-flux reactors.', 'Multi-column ion exchange in hot cells.', ['Alpha Particle X-ray Spectrometer (APXS) on Mars exploration rovers', 'Precursor for synthesizing heavier transuranic elements'], [{f:'Cm2O3',n:'Curium Oxide',u:'High-density alpha radiation source'}], [{eq:'244Cm -> 240Pu + alpha',t:'Alpha Decay',d:'Produces 2.8 W/g thermal power.'}], 'Intensely radioactive alpha emitter.'],
  [97, 'Bk', 'Berkelium', 247.0, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 5f⁹ 7s²', [2,8,18,32,27,8,2], 1.30, 1259, 2900, 14.78, 170, 601.0, 50, [3,4], 'Glenn T. Seaborg, Albert Ghiorso & Stanley Thompson', 1949, 'Synthesized at UC Berkeley, essential target material for discovering Tennessine (117).', 'High-flux isotope reactor synthesis at Oak Ridge National Lab.', 'High-pressure ion exchange separation.', ['Target material in particle accelerators for discovering element 117 (Tennessine)', 'Fundamental actinide chemistry research'], [{f:'BkO2',n:'Berkelium Dioxide',u:'Actinide coordination compound'}], [{eq:'249Bk + 48Ca -> 294Ts + 3n',t:'Fusion Synthesis',d:'Discovered element 117.'}], 'Dangerous radioactive actinide.'],
  [98, 'Cf', 'Californium', 251.0, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 5f¹⁰ 7s²', [2,8,18,32,28,8,2], 1.30, 1173, 1743, 15.1, 170, 608.0, 50, [2,3,4], 'Glenn T. Seaborg, Albert Ghiorso & Stanley Thompson', 1950, 'Tremendous spontaneous neutron emitter (1 microgram emits 2.3 million neutrons per second).', 'Synthesized in the High Flux Isotope Reactor (HFIR) at Oak Ridge.', 'Multi-stage solvent extraction in shielded hot cells.', ['Neutron startup source for commercial nuclear reactors', 'Neutron Activation Analysis (NAA) for airport luggage and oil wells', 'Brachytherapy for cervical cancer'], [{f:'252Cf',n:'Californium-252',u:'Compact portable neutron emitter'}], [{eq:'252Cf -> spontaneous fission + neutrons',t:'Spontaneous Fission',d:'Generates intense neutron flux.'}], 'Extreme radiation hazard; requires thick paraffin/water neutron shielding.'],
  [99, 'Es', 'Einsteinium', 252.0, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 5f¹¹ 7s²', [2,8,18,32,29,8,2], 1.30, 1133, 1269, 8.84, 170, 619.0, 50, [2,3], 'Albert Ghiorso and team', 1952, 'Discovered in the radioactive debris of the first thermonuclear hydrogen bomb test (Ivy Mike).', 'Debris of thermonuclear explosion Ivy Mike; now produced in High Flux Isotope Reactor.', 'Chromatographic separation.', ['Fundamental research on heavy actinide bonding and 5f electron behavior', 'Synthesizing mendelevium in cyclotrons'], [{f:'EsCl3',n:'Einsteinium Trichloride',u:'Sub-microgram structural study compound'}], [{eq:'253Es + alpha -> 256Md + n',t:'First Synthesis of Md',d:'Discovered element 101.'}], 'Intensely radioactive with high self-damage rate.'],
  [100, 'Fm', 'Fermium', 257.0, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 5f¹² 7s²', [2,8,18,32,30,8,2], 1.30, 1800, null, null, 170, 627.0, 50, [2,3], 'Albert Ghiorso and team', 1952, 'Heaviest element that can be synthesized by successive neutron capture in nuclear reactors.', 'Ivy Mike thermonuclear debris and High Flux Isotope Reactor.', 'Ion exchange elution.', ['Scientific research on the limits of nuclear stability and spontaneous fission'], [{f:'FmCl2',n:'Fermium(II) Chloride',u:'Radiochemical tracer'}], [{eq:'257Fm -> spontaneous fission',t:'Nuclear Decay',d:'Fermium barrier in neutron capture.'}], 'Highly radioactive; available only in picogram quantities.'],
  [101, 'Md', 'Mendelevium', 258.0, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 5f¹³ 7s²', [2,8,18,32,31,8,2], 1.30, 1100, null, null, 170, 635.0, 50, [2,3], 'Albert Ghiorso, Glenn T. Seaborg and team', 1955, 'First element synthesized atom-by-atom (17 atoms produced in original experiment), named after Dmitri Mendeleev.', 'Cyclotron alpha bombardment of einsteinium-253.', 'Single-atom cation-exchange elution.', ['Scientific study of anomalous divalent actinide chemistry and nuclear fission dynamics'], [{f:'Md2+',n:'Mendelevium(II) ion',u:'Unusually stable divalent aqueous state'}], [{eq:'253Es + 4He -> 256Md + n',t:'Discovery Reaction',d:'Atom-at-a-time discovery.'}], 'High radioactivity; exists only in single-atom quantities.'],
  [102, 'No', 'Nobelium', 259.0, 'actinide', 3, 7, 'f', 'Solid', '[Rn] 5f¹⁴ 7s²', [2,8,18,32,32,8,2], 1.30, 1100, null, null, 170, 642.0, 50, [2,3], 'Georgy Flerov, Albert Ghiorso and team', 1966, 'Penultimate actinide, surprisingly stable in the +2 oxidation state due to filled 5f14 shell.', 'Heavy-ion cyclotron bombardment of curium with carbon or oxygen ions.', 'Gas-jet recoil collection.', ['Fundamental study of relativistic electron shell contractions'], [{f:'NoCl2',n:'Nobelium Dichloride',u:'Favors +2 state over +3'}], [{eq:'246Cm + 12C -> 254No + 4n',t:'Heavy-Ion Fusion',d:'Cyclotron discovery.'}], 'Highly radioactive; atomic-scale research only.'],
  [103, 'Lr', 'Lawrencium', 266.0, 'actinide', 3, 7, 'd', 'Solid', '[Rn] 5f¹⁴ 7s² 7p¹', [2,8,18,32,32,8,3], 1.30, 1900, null, null, 170, 470.0, 50, [3], 'Albert Ghiorso and team', 1961, 'Final actinide, has an anomalous 7s2 7p1 valence configuration due to strong relativistic effects.', 'Heavy-ion bombardment of californium with boron ions.', 'Online isotope separator.', ['Confirming relativistic stabilization of the 7p1/2 orbital'], [{f:'LrCl3',n:'Lawrencium Trichloride',u:'Aqueous +3 behavior'}], [{eq:'252Cf + 11B -> 258Lr + 5n',t:'Fusion',d:'Discovered at Berkeley.'}], 'Radioactive synthetic element.'],

  // 104-118 (Transactinides / Superheavy Elements)
  [104, 'Rf', 'Rutherfordium', 267.0, 'transition-metal', 4, 7, 'd', 'Solid', '[Rn] 5f¹⁴ 6d² 7s²', [2,8,18,32,32,10,2], null, 2400, 5800, 23.2, 160, 580.0, null, [4], 'Dubna & Berkeley laboratories', 1969, 'First transactinide superheavy element, named after Ernest Rutherford, forms volatile tetrachloride.', 'Particle accelerator bombardment of plutonium with neon or californium with carbon.', 'Gas-phase chromatography.', ['Testing relativistic chemical bonding trends in group 4 superheavy elements'], [{f:'RfCl4',n:'Rutherfordium Tetrachloride',u:'Volatile gas-phase chloride'}], [{eq:'249Cf + 12C -> 257Rf + 4n',t:'Heavy Ion Fusion',d:'Discovery reaction.'}], 'Extreme radioactivity; atom-at-a-time quantities.'],
  [105, 'Db', 'Dubnium', 268.0, 'transition-metal', 5, 7, 'd', 'Solid', '[Rn] 5f¹⁴ 6d³ 7s²', [2,8,18,32,32,11,2], null, null, null, 29.3, 150, null, null, [5], 'Dubna & Berkeley laboratories', 1970, 'Superheavy group 5 element named after Dubna, Russia, home of the Flerov Laboratory.', 'Accelerator bombardment of americium-243 with neon-22.', 'Fast aqueous chromatography.', ['Comparing superheavy group 5 behavior against tantalum and niobium'], [{f:'DbBr5',n:'Dubnium Pentabromide',u:'Gas phase halide'}], [{eq:'243Am + 22Ne -> 260Db + 5n',t:'Cold Fusion',d:'Discovery reaction.'}], 'Extreme radioactivity.'],
  [106, 'Sg', 'Seaborgium', 269.0, 'transition-metal', 6, 7, 'd', 'Solid', '[Rn] 5f¹⁴ 6d⁴ 7s²', [2,8,18,32,32,12,2], null, null, null, 35.0, 140, null, null, [6], 'Lawrence Berkeley Laboratory', 1974, 'Named after Nobel laureate Glenn T. Seaborg while he was still living, behaves like tungsten.', 'Bombardment of californium-249 with oxygen-18.', 'Automated gas chromatography.', ['Synthesizing hexacarbonyl complexes Sg(CO)6 confirming group 6 behavior'], [{f:'Sg(CO)6',n:'Seaborgium Hexacarbonyl',u:'Volatile organometallic complex'}], [{eq:'249Cf + 18O -> 263Sg + 4n',t:'Fusion',d:'Heavy-ion fusion synthesis.'}], 'Extreme radioactivity.'],
  [107, 'Bh', 'Bohrium', 270.0, 'transition-metal', 7, 7, 'd', 'Solid', '[Rn] 5f¹⁴ 6d⁵ 7s²', [2,8,18,32,32,13,2], null, null, null, 37.1, 140, null, null, [7], 'GSI Darmstadt, Germany', 1981, 'Named after quantum physicist Niels Bohr, forms volatile oxychloride BhO3Cl.', 'Cold fusion of bismuth-209 target with chromium-54 projectile.', 'Fast gas-phase chemical chromatography.', ['Confirming volatility and formation of volatile oxychloride matching rhenium'], [{f:'BhO3Cl',n:'Bohrium Oxychloride',u:'Gas-phase chromatography marker'}], [{eq:'209Bi + 54Cr -> 262Bh + n',t:'Cold Fusion',d:'Discovered at GSI.'}], 'Extreme radioactivity.'],
  [108, 'Hs', 'Hassium', 269.0, 'transition-metal', 8, 7, 'd', 'Solid', '[Rn] 5f¹⁴ 6d⁶ 7s²', [2,8,18,32,32,14,2], null, null, null, 41.0, 135, null, null, [8], 'GSI Darmstadt, Germany', 1984, 'Named after the German state of Hesse, forms volatile tetroxide HsO4 analogous to osmium.', 'Cold fusion of lead-208 with iron-58.', 'Gas-phase thermochromatography.', ['Confirming HsO4 deposition on silicon nitride surfaces at -44°C'], [{f:'HsO4',n:'Hassium Tetroxide',u:'Volatile tetroxide matching OsO4'}], [{eq:'208Pb + 58Fe -> 265Hs + n',t:'Cold Fusion',d:'Discovered at GSI.'}], 'Extreme radioactivity.'],
  [109, 'Mt', 'Meitnerium', 278.0, 'unknown', 9, 7, 'd', 'Solid', '[Rn] 5f¹⁴ 6d⁷ 7s²', [2,8,18,32,32,15,2], null, null, null, 37.4, 135, null, null, [1,3], 'GSI Darmstadt, Germany', 1982, 'Named in honor of Austrian-Swedish physicist Lise Meitner, discoverer of nuclear fission.', 'Bombardment of bismuth-209 with iron-58.', 'Single-atom recoil separator.', ['Nuclear physics exploration of shell closures around N=162'], [{f:'Mt',n:'Elemental Meitnerium',u:'Synthetic transactinide'}], [{eq:'209Bi + 58Fe -> 266Mt + n',t:'Heavy-Ion Fusion',d:'Single atom detected at GSI.'}], 'Extreme radioactivity.'],
  [110, 'Ds', 'Darmstadtium', 281.0, 'unknown', 10, 7, 'd', 'Solid', '[Rn] 5f¹⁴ 6d⁸ 7s²', [2,8,18,32,32,16,2], null, null, null, 34.8, 130, null, null, [2,4], 'GSI Darmstadt, Germany', 1994, 'Named after the city of Darmstadt, where GSI Helmholtz Centre for Heavy Ion Research is located.', 'Fusion of lead-208 target with nickel-62 beam.', 'SHIP recoil separator.', ['Nuclear structure studies of superheavy atomic nuclei'], [{f:'DsF6',n:'Darmstadtium Hexafluoride',u:'Predicted noble compound'}], [{eq:'208Pb + 62Ni -> 269Ds + n',t:'Fusion',d:'Discovered at GSI.'}], 'Extreme radioactivity.'],
  [111, 'Rg', 'Roentgenium', 282.0, 'unknown', 11, 7, 'd', 'Solid', '[Rn] 5f¹⁴ 6d⁹ 7s²', [2,8,18,32,32,17,2], null, null, null, 28.7, 125, null, null, [3], 'GSI Darmstadt, Germany', 1994, 'Named after Wilhelm Conrad Röntgen, discoverer of X-rays; superheavy coinage metal.', 'Fusion of bismuth-209 with nickel-64.', 'Velocity filter SHIP separator.', ['Studying relativistic expansion of the 6d shell and stabilization of 7s'], [{f:'Rg',n:'Elemental Roentgenium',u:'Superheavy group 11 metal'}], [{eq:'209Bi + 64Ni -> 272Rg + n',t:'Fusion',d:'Discovered at GSI.'}], 'Extreme radioactivity.'],
  [112, 'Cn', 'Copernicium', 285.0, 'post-transition-metal', 12, 7, 'd', 'Liquid', '[Rn] 5f¹⁴ 6d¹⁰ 7s²', [2,8,18,32,32,18,2], null, 283, 340, 14.0, 122, null, null, [2], 'GSI Darmstadt, Germany', 1996, 'Named after astronomer Nicolaus Copernicus; relativistic effects make it behave like a volatile noble-gas-like liquid metal.', 'Fusion of lead-208 with zinc-70.', 'Gas-phase adsorption on gold surfaces.', ['Proving relativistic inertness of 7s2 valence electrons causing extreme volatility'], [{f:'Cn-Au bond',n:'Copernicium-Gold Adsorption',u:'Thermochromatographic surface interaction'}], [{eq:'208Pb + 70Zn -> 277Cn + n',t:'Cold Fusion',d:'Discovered at GSI.'}], 'Extreme radioactivity.'],
  [113, 'Nh', 'Nihonium', 286.0, 'unknown', 13, 7, 'p', 'Solid', '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹', [2,8,18,32,32,18,3], null, 700, 1400, 16.0, 136, null, null, [1,3], 'RIKEN, Japan (Kosuke Morita and team)', 2004, 'First chemical element discovered in Asia, named after Nihon (Japan) at RIKEN linear accelerator.', 'Fusion of bismuth-209 with zinc-70 beam over 9 years of accelerator runtime.', 'GARIS gas-filled recoil separator.', ['Nuclear decay chain mapping connecting to known dubnium isotopes'], [{f:'NhOH',n:'Nihonium Hydroxide',u:'Predicted volatile hydroxide'}], [{eq:'209Bi + 70Zn -> 278Nh + n',t:'Heavy-Ion Cold Fusion',d:'RIKEN milestone discovery.'}], 'Extreme radioactivity.'],
  [114, 'Fl', 'Flerovium', 289.0, 'post-transition-metal', 14, 7, 'p', 'Solid', '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²', [2,8,18,32,32,18,4], null, 340, 420, 9.928, 143, null, null, [2], 'Joint Institute for Nuclear Research (Dubna) & LLNL', 1998, 'Named after Flerov Laboratory; exhibits pronounced noble-gas-like volatility due to spin-orbit splitting.', 'Hot fusion of plutonium-244 with calcium-48.', 'Cryo-online detector arrays.', ['Investigating the predicted Island of Stability around N=184'], [{f:'Fl',n:'Elemental Flerovium',u:'Relativistically stabilized closed-subshell atom'}], [{eq:'244Pu + 48Ca -> 289Fl + 3n',t:'Hot Fusion',d:'Dubna-LLNL discovery.'}], 'Extreme radioactivity.'],
  [115, 'Mc', 'Moscovium', 290.0, 'unknown', 15, 7, 'p', 'Solid', '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³', [2,8,18,32,32,18,5], null, 670, 1400, 13.5, 162, null, null, [1,3], 'Dubna & LLNL & Vanderbilt University', 2003, 'Named after Moscow Oblast, Russia; decays into nihonium via successive alpha emissions.', 'Bombardment of americium-243 with calcium-48.', 'Gas-filled separator DGFRS.', ['Studying superheavy alpha decay trajectories towards the island of stability'], [{f:'McCl',n:'Moscovium Monochloride',u:'Predicted stable monovalent state'}], [{eq:'243Am + 48Ca -> 288Mc + 3n',t:'Hot Fusion',d:'Discovery reaction.'}], 'Extreme radioactivity.'],
  [116, 'Lv', 'Livermorium', 293.0, 'unknown', 16, 7, 'p', 'Solid', '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴', [2,8,18,32,32,18,6], null, 708, 1085, 12.9, 175, null, null, [2,4], 'Dubna & Lawrence Livermore National Laboratory', 2000, 'Named after Lawrence Livermore National Laboratory in Livermore, California.', 'Fusion of curium-248 with calcium-48.', 'Recoil separator DGFRS.', ['Synthesizing neutron-rich superheavy nuclei approaching N=184'], [{f:'Lv',n:'Elemental Livermorium',u:'Group 16 superheavy atom'}], [{eq:'248Cm + 48Ca -> 293Lv + 3n',t:'Hot Fusion',d:'Discovery reaction.'}], 'Extreme radioactivity.'],
  [117, 'Ts', 'Tennessine', 294.0, 'unknown', 17, 7, 'p', 'Solid', '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵', [2,8,18,32,32,18,7], null, 723, 883, 7.2, 165, null, null, [-1,1,3], 'Dubna, LLNL, Vanderbilt & Oak Ridge National Lab', 2010, 'Second heaviest element known, named after Tennessee for Oak Ridge contribution of Berkelium target.', 'Fusion of berkelium-249 target with calcium-48 beam.', 'Gas-filled recoil separator.', ['Exploring halogen group trends under massive spin-orbit relativistic coupling'], [{f:'TsF3',n:'Tennessine Trifluoride',u:'Predicted halide'}], [{eq:'249Bk + 48Ca -> 294Ts + 3n',t:'Hot Fusion',d:'Synthesized with rare berkelium target.'}], 'Extreme radioactivity.'],
  [118, 'Og', 'Oganesson', 294.0, 'noble-gas', 18, 7, 'p', 'Solid', '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶', [2,8,18,32,32,18,8], null, 325, 350, 5.0, 152, 860.0, 5.4, [0,2,4], 'Dubna & Lawrence Livermore National Laboratory', 2002, 'Heaviest element on the periodic table, named after academician Yuri Oganessian; relativistic effects make it a semiconductor solid.', 'Hot fusion of californium-249 target with calcium-48 beam.', 'Gas-filled recoil separator DGFRS.', ['Studying uniform Thomas-Fermi electron density smear and high polarizability in superheavy elements'], [{f:'OgF4',n:'Oganesson Tetrafluoride',u:'Predicted tetrahedral fluoride'}], [{eq:'249Cf + 48Ca -> 294Og + 3n',t:'Milestone Fusion',d:'Synthesized heaviest atom known to humankind.'}], 'Extreme radioactivity; half-life under 1 millisecond. Exists only in atom-at-a-time synthesis.']
];

for (const b of baseData) {
  const [
    n, s, name, m, cat, g, p, bl, st, ec, sh, en, mp, bp, d, ar, ie, ea, ox, by, yr,
    sum, occ, ext, app, comp, rx, saf
  ] = b;

  elements.push({
    number: n,
    symbol: s,
    name: name,
    atomicMass: m,
    category: cat,
    group: g,
    period: p,
    block: bl,
    state: st,
    electronConfiguration: ec,
    electronsPerShell: sh,
    electronegativity: en,
    meltingPoint: mp,
    boilingPoint: bp,
    density: d,
    atomicRadius: ar,
    ionizationEnergy: ie,
    electronAffinity: ea,
    oxidationStates: ox,
    discoveredBy: by,
    yearDiscovered: yr,
    summary: sum,
    occurrence: occ,
    extraction: ext,
    applications: app,
    importantCompounds: comp,
    reactions: rx,
    safety: saf
  });
}

// Sort by atomic number ascending
elements.sort((a, b) => a.number - b.number);

console.log(`Generated ${elements.length} elements.`);

// Write out to src/data/elementsData.js
const outputPath = path.resolve('./src/data/elementsData.js');
const dir = path.dirname(outputPath);
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

const fileContent = `// src/data/elementsData.js
// ChemNexus Comprehensive 118-Element Dataset
// Verified scientific properties, electronic configurations, occurrence, extraction, applications, and reactions.

export const elementsData = ${JSON.stringify(elements, null, 2)};

export default elementsData;
`;

fs.writeFileSync(outputPath, fileContent, 'utf-8');
console.log(`Wrote complete 118 elements dataset to ${outputPath}`);
